/*NOCHKSRC*/
//==============================================================================
//
// PLEASE DO NOT EDIT; THIS FILE WAS AUTOMATICALLY GENERATED BY GENCLASS 2.0.24
//
//==============================================================================

#ifndef _cimple_CIM_ConnectorOnPackage_h
#define _cimple_CIM_ConnectorOnPackage_h

#include <cimple/cimple.h>
#include "CIM_Container.h"
#include "CIM_PhysicalPackage.h"
#include "CIM_PhysicalConnector.h"

CIMPLE_NAMESPACE_BEGIN

// CIM_ConnectorOnPackage keys:

/*[1194]*/
class CIM_ConnectorOnPackage : public Instance
{
public:
    // CIM_Component features:
    CIM_PhysicalPackage* GroupComponent;
    CIM_PhysicalConnector* PartComponent;

    // CIM_Container features:
    Property<String> LocationWithinContainer;

    // CIM_ConnectorOnPackage features:

    CIMPLE_CLASS(CIM_ConnectorOnPackage)
};

CIMPLE_NAMESPACE_END

#endif /* _cimple_CIM_ConnectorOnPackage_h */
