/*NOCHKSRC*/
//==============================================================================
//
// PLEASE DO NOT EDIT; THIS FILE WAS AUTOMATICALLY GENERATED BY GENCLASS 2.0.24
//
//==============================================================================

#ifndef _cimple_CIM_Collection_h
#define _cimple_CIM_Collection_h

#include <cimple/cimple.h>
#include "CIM_ManagedElement.h"

CIMPLE_NAMESPACE_BEGIN

// CIM_Collection keys:

/*[1194]*/
class CIM_Collection : public Instance
{
public:
    // CIM_ManagedElement features:
    Property<String> InstanceID;
    Property<String> Caption;
    Property<String> Description;
    Property<String> ElementName;
    Property<uint64> Generation;

    // CIM_Collection features:

    CIMPLE_CLASS(CIM_Collection)
};

CIMPLE_NAMESPACE_END

#endif /* _cimple_CIM_Collection_h */
