/*NOCHKSRC*/
//==============================================================================
//
// PLEASE DO NOT EDIT; THIS FILE WAS AUTOMATICALLY GENERATED BY GENCLASS 2.0.24
//
//==============================================================================

#include <cimple/Meta_Class.h>
#include <cimple/Meta_Property.h>
#include <cimple/Meta_Reference.h>
#include "CIM_Capabilities.h"

CIMPLE_NAMESPACE_BEGIN

using namespace cimple;

extern const Meta_Repository __meta_repository_0DDA66E0FF471BAB95C366A9360C9285;

/*[1568]*/
extern const Meta_Property
_CIM_Capabilities_InstanceID;

/*[1591]*/
const Meta_Property
_CIM_Capabilities_InstanceID =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_KEY|CIMPLE_FLAG_READ,
    "InstanceID",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    STRING,
    0, /* subscript */
    CIMPLE_OFF(CIM_Capabilities,InstanceID),
    0, /* value */
};

/*[1568]*/
extern const Meta_Property
_CIM_ManagedElement_Caption;

/*[1568]*/
extern const Meta_Property
_CIM_ManagedElement_Description;

/*[1568]*/
extern const Meta_Property
_CIM_Capabilities_ElementName;

/*[1591]*/
const Meta_Property
_CIM_Capabilities_ElementName =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_READ|CIMPLE_FLAG_REQUIRED,
    "ElementName",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    STRING,
    0, /* subscript */
    CIMPLE_OFF(CIM_Capabilities,ElementName),
    0, /* value */
};

/*[1568]*/
extern const Meta_Property
_CIM_ManagedElement_Generation;

/*[1846]*/
static const Meta_Reference
_CIM_Capabilities_CreateGoalSettings_TemplateGoalSettings =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_REFERENCE|CIMPLE_FLAG_EMBEDDED_INSTANCE|CIMPLE_FLAG_IN,
    "TemplateGoalSettings",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    -1, /* subscript */
    &CIM_SettingData::static_meta_class,
    CIMPLE_OFF(CIM_Capabilities_CreateGoalSettings_method,TemplateGoalSettings)
};

/*[1846]*/
static const Meta_Reference
_CIM_Capabilities_CreateGoalSettings_SupportedGoalSettings =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_REFERENCE|CIMPLE_FLAG_EMBEDDED_INSTANCE|CIMPLE_FLAG_IN|CIMPLE_FLAG_OUT,
    "SupportedGoalSettings",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    -1, /* subscript */
    &CIM_SettingData::static_meta_class,
    CIMPLE_OFF(CIM_Capabilities_CreateGoalSettings_method,SupportedGoalSettings)
};

/*[1935]*/
static const Meta_Property
_CIM_Capabilities_CreateGoalSettings_return_value =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "return_value",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT16,
    0,
    CIMPLE_OFF(CIM_Capabilities_CreateGoalSettings_method,return_value),
    0, /* value */
};

/*[1911]*/
static Meta_Feature* _CIM_Capabilities_CreateGoalSettings_MFA[] =
{
    (Meta_Feature*)(void*)&_CIM_Capabilities_CreateGoalSettings_TemplateGoalSettings,
    (Meta_Feature*)(void*)&_CIM_Capabilities_CreateGoalSettings_SupportedGoalSettings,
    (Meta_Feature*)(void*)&_CIM_Capabilities_CreateGoalSettings_return_value
};

/*[2113]*/
const Meta_Method
CIM_Capabilities_CreateGoalSettings_method::static_meta_class =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_METHOD|CIMPLE_FLAG_EXPERIMENTAL,
    "CreateGoalSettings",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _CIM_Capabilities_CreateGoalSettings_MFA,
    CIMPLE_ARRAY_SIZE(_CIM_Capabilities_CreateGoalSettings_MFA),
    sizeof(CIM_Capabilities_CreateGoalSettings_method),
    UINT16,
};

/*[2291]*/
static Meta_Feature* _CIM_Capabilities_MFA[] =
{
    (Meta_Feature*)(void*)&_CIM_Capabilities_InstanceID,
    (Meta_Feature*)(void*)&_CIM_ManagedElement_Caption,
    (Meta_Feature*)(void*)&_CIM_ManagedElement_Description,
    (Meta_Feature*)(void*)&_CIM_Capabilities_ElementName,
    (Meta_Feature*)(void*)&_CIM_ManagedElement_Generation,
    (Meta_Feature*)(void*)&CIM_Capabilities_CreateGoalSettings_method::static_meta_class,
};

/*[2338]*/
static const Meta_Feature_Local _locals[] =
{
    {1},
    {0},
    {0},
    {1},
    {0},
    {1},
};

/*[2358]*/
const Meta_Class CIM_Capabilities::static_meta_class =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_CLASS|CIMPLE_FLAG_ABSTRACT,
    "CIM_Capabilities",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _CIM_Capabilities_MFA,
    CIMPLE_ARRAY_SIZE(_CIM_Capabilities_MFA),
    sizeof(CIM_Capabilities),
    _locals,
    &CIM_ManagedElement::static_meta_class,
    1, /* num_keys */
    &__meta_repository_0DDA66E0FF471BAB95C366A9360C9285,
};

CIMPLE_NAMESPACE_END

