/*NOCHKSRC*/
//==============================================================================
//
// PLEASE DO NOT EDIT; THIS FILE WAS AUTOMATICALLY GENERATED BY GENCLASS 2.0.24
//
//==============================================================================

#ifndef _cimple_CIM_ReferencedSpecification_h
#define _cimple_CIM_ReferencedSpecification_h

#include <cimple/cimple.h>
#include "CIM_Dependency.h"
#include "CIM_RegisteredSpecification.h"
#include "CIM_RegisteredSpecification.h"

CIMPLE_NAMESPACE_BEGIN

// CIM_ReferencedSpecification keys:

/*[1194]*/
class CIM_ReferencedSpecification : public Instance
{
public:
    // CIM_Dependency features:
    CIM_RegisteredSpecification* Antecedent;
    CIM_RegisteredSpecification* Dependent;

    // CIM_ReferencedSpecification features:

    CIMPLE_CLASS(CIM_ReferencedSpecification)
};

CIMPLE_NAMESPACE_END

#endif /* _cimple_CIM_ReferencedSpecification_h */
