/*NOCHKSRC*/
//==============================================================================
//
// PLEASE DO NOT EDIT; THIS FILE WAS AUTOMATICALLY GENERATED BY GENCLASS 2.0.24
//
//==============================================================================

#include <cimple/Meta_Class.h>
#include <cimple/Meta_Property.h>
#include <cimple/Meta_Reference.h>
#include "CIM_DiagnosticTest.h"

CIMPLE_NAMESPACE_BEGIN

using namespace cimple;

extern const Meta_Repository __meta_repository_0DDA66E0FF471BAB95C366A9360C9285;

/*[1568]*/
extern const Meta_Property
_CIM_ManagedElement_InstanceID;

/*[1568]*/
extern const Meta_Property
_CIM_ManagedElement_Caption;

/*[1568]*/
extern const Meta_Property
_CIM_ManagedElement_Description;

/*[1568]*/
extern const Meta_Property
_CIM_ManagedElement_ElementName;

/*[1568]*/
extern const Meta_Property
_CIM_ManagedElement_Generation;

/*[1568]*/
extern const Meta_Property
_CIM_ManagedSystemElement_InstallDate;

/*[1568]*/
extern const Meta_Property
_CIM_Service_Name;

/*[1568]*/
extern const Meta_Property
_CIM_ManagedSystemElement_OperationalStatus;

/*[1568]*/
extern const Meta_Property
_CIM_ManagedSystemElement_StatusDescriptions;

/*[1568]*/
extern const Meta_Property
_CIM_ManagedSystemElement_Status;

/*[1568]*/
extern const Meta_Property
_CIM_ManagedSystemElement_HealthState;

/*[1568]*/
extern const Meta_Property
_CIM_ManagedSystemElement_CommunicationStatus;

/*[1568]*/
extern const Meta_Property
_CIM_ManagedSystemElement_DetailedStatus;

/*[1568]*/
extern const Meta_Property
_CIM_ManagedSystemElement_OperatingStatus;

/*[1568]*/
extern const Meta_Property
_CIM_ManagedSystemElement_PrimaryStatus;

/*[1568]*/
extern const Meta_Property
_CIM_EnabledLogicalElement_EnabledState;

/*[1568]*/
extern const Meta_Property
_CIM_EnabledLogicalElement_OtherEnabledState;

/*[1568]*/
extern const Meta_Property
_CIM_EnabledLogicalElement_RequestedState;

/*[1568]*/
extern const Meta_Property
_CIM_EnabledLogicalElement_EnabledDefault;

/*[1568]*/
extern const Meta_Property
_CIM_EnabledLogicalElement_TimeOfLastStateChange;

/*[1568]*/
extern const Meta_Property
_CIM_EnabledLogicalElement_AvailableRequestedStates;

/*[1568]*/
extern const Meta_Property
_CIM_EnabledLogicalElement_TransitioningToState;

/*[1568]*/
extern const Meta_Property
_CIM_Service_SystemCreationClassName;

/*[1568]*/
extern const Meta_Property
_CIM_Service_SystemName;

/*[1568]*/
extern const Meta_Property
_CIM_Service_CreationClassName;

/*[1568]*/
extern const Meta_Property
_CIM_Service_PrimaryOwnerName;

/*[1568]*/
extern const Meta_Property
_CIM_Service_PrimaryOwnerContact;

/*[1568]*/
extern const Meta_Property
_CIM_Service_StartMode;

/*[1568]*/
extern const Meta_Property
_CIM_Service_Started;

/*[1568]*/
extern const Meta_Property
_CIM_DiagnosticTest_Characteristics;

/*[1591]*/
const Meta_Property
_CIM_DiagnosticTest_Characteristics =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_READ,
    "Characteristics",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT16,
    -1, /* subscript */
    CIMPLE_OFF(CIM_DiagnosticTest,Characteristics),
    0, /* value */
};

/*[1568]*/
extern const Meta_Property
_CIM_DiagnosticTest_OtherCharacteristicDescription;

/*[1591]*/
const Meta_Property
_CIM_DiagnosticTest_OtherCharacteristicDescription =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_READ,
    "OtherCharacteristicDescription",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    STRING,
    0, /* subscript */
    CIMPLE_OFF(CIM_DiagnosticTest,OtherCharacteristicDescription),
    0, /* value */
};

/*[1568]*/
extern const Meta_Property
_CIM_DiagnosticTest_OtherCharacteristicsDescriptions;

/*[1591]*/
const Meta_Property
_CIM_DiagnosticTest_OtherCharacteristicsDescriptions =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_READ,
    "OtherCharacteristicsDescriptions",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    STRING,
    -1, /* subscript */
    CIMPLE_OFF(CIM_DiagnosticTest,OtherCharacteristicsDescriptions),
    0, /* value */
};

/*[1568]*/
extern const Meta_Property
_CIM_DiagnosticTest_IsInUse;

/*[1591]*/
const Meta_Property
_CIM_DiagnosticTest_IsInUse =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_READ,
    "IsInUse",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    BOOLEAN,
    0, /* subscript */
    CIMPLE_OFF(CIM_DiagnosticTest,IsInUse),
    0, /* value */
};

/*[1568]*/
extern const Meta_Property
_CIM_DiagnosticTest_ResourcesUsed;

/*[1591]*/
const Meta_Property
_CIM_DiagnosticTest_ResourcesUsed =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_READ,
    "ResourcesUsed",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT16,
    -1, /* subscript */
    CIMPLE_OFF(CIM_DiagnosticTest,ResourcesUsed),
    0, /* value */
};

/*[1568]*/
extern const Meta_Property
_CIM_DiagnosticTest_TestTypes;

/*[1591]*/
const Meta_Property
_CIM_DiagnosticTest_TestTypes =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_READ,
    "TestTypes",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT16,
    -1, /* subscript */
    CIMPLE_OFF(CIM_DiagnosticTest,TestTypes),
    0, /* value */
};

/*[1568]*/
extern const Meta_Property
_CIM_DiagnosticTest_OtherTestTypesDescriptions;

/*[1591]*/
const Meta_Property
_CIM_DiagnosticTest_OtherTestTypesDescriptions =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_READ,
    "OtherTestTypesDescriptions",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    STRING,
    -1, /* subscript */
    CIMPLE_OFF(CIM_DiagnosticTest,OtherTestTypesDescriptions),
    0, /* value */
};

/*[1721]*/
static const Meta_Reference
_CIM_DiagnosticTest_RunTest_SystemElement =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_REFERENCE|CIMPLE_FLAG_IN,
    "SystemElement",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    0, /* subscript */
    &CIM_ManagedSystemElement::static_meta_class,
    CIMPLE_OFF(CIM_DiagnosticTest_RunTest_method,SystemElement)
};

/*[1721]*/
static const Meta_Reference
_CIM_DiagnosticTest_RunTest_Setting =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_REFERENCE|CIMPLE_FLAG_IN,
    "Setting",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    0, /* subscript */
    &CIM_DiagnosticSetting::static_meta_class,
    CIMPLE_OFF(CIM_DiagnosticTest_RunTest_method,Setting)
};

/*[1721]*/
static const Meta_Reference
_CIM_DiagnosticTest_RunTest_Result =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_REFERENCE|CIMPLE_FLAG_OUT,
    "Result",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    0, /* subscript */
    &CIM_DiagnosticResult::static_meta_class,
    CIMPLE_OFF(CIM_DiagnosticTest_RunTest_method,Result)
};

/*[1935]*/
static const Meta_Property
_CIM_DiagnosticTest_RunTest_return_value =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "return_value",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT32,
    0,
    CIMPLE_OFF(CIM_DiagnosticTest_RunTest_method,return_value),
    0, /* value */
};

/*[1911]*/
static Meta_Feature* _CIM_DiagnosticTest_RunTest_MFA[] =
{
    (Meta_Feature*)(void*)&_CIM_DiagnosticTest_RunTest_SystemElement,
    (Meta_Feature*)(void*)&_CIM_DiagnosticTest_RunTest_Setting,
    (Meta_Feature*)(void*)&_CIM_DiagnosticTest_RunTest_Result,
    (Meta_Feature*)(void*)&_CIM_DiagnosticTest_RunTest_return_value
};

/*[2113]*/
const Meta_Method
CIM_DiagnosticTest_RunTest_method::static_meta_class =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_METHOD,
    "RunTest",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _CIM_DiagnosticTest_RunTest_MFA,
    CIMPLE_ARRAY_SIZE(_CIM_DiagnosticTest_RunTest_MFA),
    sizeof(CIM_DiagnosticTest_RunTest_method),
    UINT32,
};

/*[1721]*/
static const Meta_Reference
_CIM_DiagnosticTest_ClearResults_SystemElement =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_REFERENCE|CIMPLE_FLAG_IN,
    "SystemElement",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    0, /* subscript */
    &CIM_ManagedSystemElement::static_meta_class,
    CIMPLE_OFF(CIM_DiagnosticTest_ClearResults_method,SystemElement)
};

/*[1782]*/
static const Meta_Property
_CIM_DiagnosticTest_ClearResults_ResultsNotCleared =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "ResultsNotCleared",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    STRING,
    -1,
    CIMPLE_OFF(CIM_DiagnosticTest_ClearResults_method,ResultsNotCleared),
    0, /* value */
};

/*[1935]*/
static const Meta_Property
_CIM_DiagnosticTest_ClearResults_return_value =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "return_value",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT32,
    0,
    CIMPLE_OFF(CIM_DiagnosticTest_ClearResults_method,return_value),
    0, /* value */
};

/*[1911]*/
static Meta_Feature* _CIM_DiagnosticTest_ClearResults_MFA[] =
{
    (Meta_Feature*)(void*)&_CIM_DiagnosticTest_ClearResults_SystemElement,
    (Meta_Feature*)(void*)&_CIM_DiagnosticTest_ClearResults_ResultsNotCleared,
    (Meta_Feature*)(void*)&_CIM_DiagnosticTest_ClearResults_return_value
};

/*[2113]*/
const Meta_Method
CIM_DiagnosticTest_ClearResults_method::static_meta_class =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_METHOD,
    "ClearResults",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _CIM_DiagnosticTest_ClearResults_MFA,
    CIMPLE_ARRAY_SIZE(_CIM_DiagnosticTest_ClearResults_MFA),
    sizeof(CIM_DiagnosticTest_ClearResults_method),
    UINT32,
};

/*[1721]*/
static const Meta_Reference
_CIM_DiagnosticTest_DiscontinueTest_SystemElement =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_REFERENCE|CIMPLE_FLAG_IN,
    "SystemElement",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    0, /* subscript */
    &CIM_ManagedSystemElement::static_meta_class,
    CIMPLE_OFF(CIM_DiagnosticTest_DiscontinueTest_method,SystemElement)
};

/*[1721]*/
static const Meta_Reference
_CIM_DiagnosticTest_DiscontinueTest_Result =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_REFERENCE|CIMPLE_FLAG_IN,
    "Result",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    0, /* subscript */
    &CIM_DiagnosticResult::static_meta_class,
    CIMPLE_OFF(CIM_DiagnosticTest_DiscontinueTest_method,Result)
};

/*[1782]*/
static const Meta_Property
_CIM_DiagnosticTest_DiscontinueTest_TestingStopped =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "TestingStopped",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    BOOLEAN,
    0,
    CIMPLE_OFF(CIM_DiagnosticTest_DiscontinueTest_method,TestingStopped),
    0, /* value */
};

/*[1935]*/
static const Meta_Property
_CIM_DiagnosticTest_DiscontinueTest_return_value =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "return_value",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT32,
    0,
    CIMPLE_OFF(CIM_DiagnosticTest_DiscontinueTest_method,return_value),
    0, /* value */
};

/*[1911]*/
static Meta_Feature* _CIM_DiagnosticTest_DiscontinueTest_MFA[] =
{
    (Meta_Feature*)(void*)&_CIM_DiagnosticTest_DiscontinueTest_SystemElement,
    (Meta_Feature*)(void*)&_CIM_DiagnosticTest_DiscontinueTest_Result,
    (Meta_Feature*)(void*)&_CIM_DiagnosticTest_DiscontinueTest_TestingStopped,
    (Meta_Feature*)(void*)&_CIM_DiagnosticTest_DiscontinueTest_return_value
};

/*[2113]*/
const Meta_Method
CIM_DiagnosticTest_DiscontinueTest_method::static_meta_class =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_METHOD,
    "DiscontinueTest",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _CIM_DiagnosticTest_DiscontinueTest_MFA,
    CIMPLE_ARRAY_SIZE(_CIM_DiagnosticTest_DiscontinueTest_MFA),
    sizeof(CIM_DiagnosticTest_DiscontinueTest_method),
    UINT32,
};

/*[2291]*/
static Meta_Feature* _CIM_DiagnosticTest_MFA[] =
{
    (Meta_Feature*)(void*)&_CIM_ManagedElement_InstanceID,
    (Meta_Feature*)(void*)&_CIM_ManagedElement_Caption,
    (Meta_Feature*)(void*)&_CIM_ManagedElement_Description,
    (Meta_Feature*)(void*)&_CIM_ManagedElement_ElementName,
    (Meta_Feature*)(void*)&_CIM_ManagedElement_Generation,
    (Meta_Feature*)(void*)&_CIM_ManagedSystemElement_InstallDate,
    (Meta_Feature*)(void*)&_CIM_Service_Name,
    (Meta_Feature*)(void*)&_CIM_ManagedSystemElement_OperationalStatus,
    (Meta_Feature*)(void*)&_CIM_ManagedSystemElement_StatusDescriptions,
    (Meta_Feature*)(void*)&_CIM_ManagedSystemElement_Status,
    (Meta_Feature*)(void*)&_CIM_ManagedSystemElement_HealthState,
    (Meta_Feature*)(void*)&_CIM_ManagedSystemElement_CommunicationStatus,
    (Meta_Feature*)(void*)&_CIM_ManagedSystemElement_DetailedStatus,
    (Meta_Feature*)(void*)&_CIM_ManagedSystemElement_OperatingStatus,
    (Meta_Feature*)(void*)&_CIM_ManagedSystemElement_PrimaryStatus,
    (Meta_Feature*)(void*)&_CIM_EnabledLogicalElement_EnabledState,
    (Meta_Feature*)(void*)&_CIM_EnabledLogicalElement_OtherEnabledState,
    (Meta_Feature*)(void*)&_CIM_EnabledLogicalElement_RequestedState,
    (Meta_Feature*)(void*)&_CIM_EnabledLogicalElement_EnabledDefault,
    (Meta_Feature*)(void*)&_CIM_EnabledLogicalElement_TimeOfLastStateChange,
    (Meta_Feature*)(void*)&_CIM_EnabledLogicalElement_AvailableRequestedStates,
    (Meta_Feature*)(void*)&_CIM_EnabledLogicalElement_TransitioningToState,
    (Meta_Feature*)(void*)&CIM_EnabledLogicalElement_RequestStateChange_method::static_meta_class,
    (Meta_Feature*)(void*)&_CIM_Service_SystemCreationClassName,
    (Meta_Feature*)(void*)&_CIM_Service_SystemName,
    (Meta_Feature*)(void*)&_CIM_Service_CreationClassName,
    (Meta_Feature*)(void*)&_CIM_Service_PrimaryOwnerName,
    (Meta_Feature*)(void*)&_CIM_Service_PrimaryOwnerContact,
    (Meta_Feature*)(void*)&_CIM_Service_StartMode,
    (Meta_Feature*)(void*)&_CIM_Service_Started,
    (Meta_Feature*)(void*)&CIM_Service_StartService_method::static_meta_class,
    (Meta_Feature*)(void*)&CIM_Service_StopService_method::static_meta_class,
    (Meta_Feature*)(void*)&CIM_Service_ChangeAffectedElementsAssignedSequence_method::static_meta_class,
    (Meta_Feature*)(void*)&CIM_DiagnosticService_RunDiagnostic_method::static_meta_class,
    (Meta_Feature*)(void*)&CIM_DiagnosticService_RunDiagnosticService_method::static_meta_class,
    (Meta_Feature*)(void*)&_CIM_DiagnosticTest_Characteristics,
    (Meta_Feature*)(void*)&_CIM_DiagnosticTest_OtherCharacteristicDescription,
    (Meta_Feature*)(void*)&_CIM_DiagnosticTest_OtherCharacteristicsDescriptions,
    (Meta_Feature*)(void*)&_CIM_DiagnosticTest_IsInUse,
    (Meta_Feature*)(void*)&_CIM_DiagnosticTest_ResourcesUsed,
    (Meta_Feature*)(void*)&_CIM_DiagnosticTest_TestTypes,
    (Meta_Feature*)(void*)&_CIM_DiagnosticTest_OtherTestTypesDescriptions,
    (Meta_Feature*)(void*)&CIM_DiagnosticTest_RunTest_method::static_meta_class,
    (Meta_Feature*)(void*)&CIM_DiagnosticTest_ClearResults_method::static_meta_class,
    (Meta_Feature*)(void*)&CIM_DiagnosticTest_DiscontinueTest_method::static_meta_class,
};

/*[2338]*/
static const Meta_Feature_Local _locals[] =
{
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {1},
    {1},
    {1},
    {1},
    {1},
    {1},
    {1},
    {1},
    {1},
    {1},
};

/*[2358]*/
const Meta_Class CIM_DiagnosticTest::static_meta_class =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_CLASS,
    "CIM_DiagnosticTest",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _CIM_DiagnosticTest_MFA,
    CIMPLE_ARRAY_SIZE(_CIM_DiagnosticTest_MFA),
    sizeof(CIM_DiagnosticTest),
    _locals,
    &CIM_DiagnosticService::static_meta_class,
    4, /* num_keys */
    &__meta_repository_0DDA66E0FF471BAB95C366A9360C9285,
};

CIMPLE_NAMESPACE_END

