/*NOCHKSRC*/
//==============================================================================
//
// PLEASE DO NOT EDIT; THIS FILE WAS AUTOMATICALLY GENERATED BY GENCLASS 2.0.24
//
//==============================================================================

#ifndef _cimple_CIM_SettingData_h
#define _cimple_CIM_SettingData_h

#include <cimple/cimple.h>
#include "CIM_ManagedElement.h"

CIMPLE_NAMESPACE_BEGIN

// CIM_SettingData keys:
//     InstanceID

/*[1194]*/
class CIM_SettingData : public Instance
{
public:
    // CIM_ManagedElement features:
    Property<String> InstanceID;
    Property<String> Caption;
    Property<String> Description;
    Property<String> ElementName;

    // CIM_SettingData features:

    CIMPLE_CLASS(CIM_SettingData)
};

CIMPLE_NAMESPACE_END

#endif /* _cimple_CIM_SettingData_h */
