/*NOCHKSRC*/
//==============================================================================
//
// PLEASE DO NOT EDIT; THIS FILE WAS AUTOMATICALLY GENERATED BY GENCLASS 2.0.24
//
//==============================================================================

#include <cimple/Meta_Class.h>
#include <cimple/Meta_Property.h>
#include <cimple/Meta_Reference.h>
#include "CIM_ElementSoftwareIdentity.h"

CIMPLE_NAMESPACE_BEGIN

using namespace cimple;

extern const Meta_Repository __meta_repository_5122E1D89D3817F3AE783FBE02157763;

/*[1653]*/
extern const Meta_Reference
_CIM_ElementSoftwareIdentity_Antecedent;

/*[1664]*/
const Meta_Reference
_CIM_ElementSoftwareIdentity_Antecedent =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_REFERENCE|CIMPLE_FLAG_KEY,
    "Antecedent",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    0, /* subscript */
    &CIM_SoftwareIdentity::static_meta_class,
    CIMPLE_OFF(CIM_ElementSoftwareIdentity,Antecedent)
};

/*[1653]*/
extern const Meta_Reference
_CIM_ElementSoftwareIdentity_Dependent;

/*[1664]*/
const Meta_Reference
_CIM_ElementSoftwareIdentity_Dependent =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_REFERENCE|CIMPLE_FLAG_KEY,
    "Dependent",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    0, /* subscript */
    &CIM_ManagedElement::static_meta_class,
    CIMPLE_OFF(CIM_ElementSoftwareIdentity,Dependent)
};

/*[1568]*/
extern const Meta_Property
_CIM_ElementSoftwareIdentity_UpgradeCondition;

/*[1591]*/
const Meta_Property
_CIM_ElementSoftwareIdentity_UpgradeCondition =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_READ,
    "UpgradeCondition",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT16,
    0, /* subscript */
    CIMPLE_OFF(CIM_ElementSoftwareIdentity,UpgradeCondition),
    0, /* value */
};

/*[1568]*/
extern const Meta_Property
_CIM_ElementSoftwareIdentity_OtherUpgradeCondition;

/*[1591]*/
const Meta_Property
_CIM_ElementSoftwareIdentity_OtherUpgradeCondition =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_READ,
    "OtherUpgradeCondition",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    STRING,
    0, /* subscript */
    CIMPLE_OFF(CIM_ElementSoftwareIdentity,OtherUpgradeCondition),
    0, /* value */
};

/*[1568]*/
extern const Meta_Property
_CIM_ElementSoftwareIdentity_ElementSoftwareStatus;

/*[1591]*/
const Meta_Property
_CIM_ElementSoftwareIdentity_ElementSoftwareStatus =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_READ,
    "ElementSoftwareStatus",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT16,
    -1, /* subscript */
    CIMPLE_OFF(CIM_ElementSoftwareIdentity,ElementSoftwareStatus),
    0, /* value */
};

/*[2291]*/
static Meta_Feature* _CIM_ElementSoftwareIdentity_MFA[] =
{
    (Meta_Feature*)(void*)&_CIM_ElementSoftwareIdentity_Antecedent,
    (Meta_Feature*)(void*)&_CIM_ElementSoftwareIdentity_Dependent,
    (Meta_Feature*)(void*)&_CIM_ElementSoftwareIdentity_UpgradeCondition,
    (Meta_Feature*)(void*)&_CIM_ElementSoftwareIdentity_OtherUpgradeCondition,
    (Meta_Feature*)(void*)&_CIM_ElementSoftwareIdentity_ElementSoftwareStatus,
};

/*[2338]*/
static const Meta_Feature_Local _locals[] =
{
    {1},
    {1},
    {1},
    {1},
    {1},
};

/*[2358]*/
const Meta_Class CIM_ElementSoftwareIdentity::static_meta_class =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_ASSOCIATION,
    "CIM_ElementSoftwareIdentity",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _CIM_ElementSoftwareIdentity_MFA,
    CIMPLE_ARRAY_SIZE(_CIM_ElementSoftwareIdentity_MFA),
    sizeof(CIM_ElementSoftwareIdentity),
    _locals,
    &CIM_Dependency::static_meta_class,
    2, /* num_keys */
    &__meta_repository_5122E1D89D3817F3AE783FBE02157763,
};

CIMPLE_NAMESPACE_END

