/*NOCHKSRC*/
//==============================================================================
//
// PLEASE DO NOT EDIT; THIS FILE WAS AUTOMATICALLY GENERATED BY GENCLASS 2.0.24
//
//==============================================================================

#ifndef _cimple_CIM_DiagnosticSettingData_h
#define _cimple_CIM_DiagnosticSettingData_h

#include <cimple/cimple.h>
#include "CIM_SettingData.h"

CIMPLE_NAMESPACE_BEGIN

// CIM_DiagnosticSettingData keys:
//     InstanceID

/*[1194]*/
class CIM_DiagnosticSettingData : public Instance
{
public:
    // CIM_ManagedElement features:
    Property<String> InstanceID;
    Property<String> Caption;
    Property<String> Description;
    Property<String> ElementName;
    Property<uint64> Generation;

    // CIM_SettingData features:
    Property<String> ConfigurationName;
    struct _ChangeableType
    {
        enum
        {
            enum_Not_Changeable___Persistent = 0,
            enum_Changeable___Transient = 1,
            enum_Changeable___Persistent = 2,
            enum_Not_Changeable___Transient = 3,
        };
        uint16 value;
        uint8 null;
    }
    ChangeableType;

    // CIM_DiagnosticSettingData features:
    Property<boolean> HaltOnError;
    Property<boolean> QuickMode;
    Property<uint8> PercentOfTestCoverage;
    Property<Array_String> LoopControlParameter;
    struct _LoopControl
    {
        enum
        {
            enum_Unknown = 0,
            enum_Other = 1,
            enum_Continuous = 2,
            enum_Count = 3,
            enum_Timer = 4,
            enum_ErrorCount = 5,
        };
        Array_uint16 value;
        uint8 null;
    }
    LoopControl;
    Property<Array_String> OtherLoopControlDescriptions;
    Property<uint32> ResultPersistence;
    struct _LogOptions
    {
        enum
        {
            enum_Unknown = 0,
            enum_Other = 1,
            enum_Results = 2,
            enum_Subtests = 3,
            enum_Actions = 4,
            enum_Warnings = 5,
            enum_Status = 6,
            enum_Device_Errors = 7,
            enum_Service_Errors = 8,
            enum_Setting_Data = 9,
            enum_Statistics = 10,
            enum_Hardware_Configuration = 11,
            enum_Software_Configuration = 12,
            enum_References = 13,
            enum_Debug = 14,
            enum_No_Log_Options = 0,
        };
        Array_uint16 value;
        uint8 null;
    }
    LogOptions;
    Property<Array_String> OtherLogOptionsDescriptions;
    struct _LogStorage
    {
        enum
        {
            enum_Unknown = 0,
            enum_Other = 1,
            enum_DiagnosticLog = 2,
            enum_MessageLog = 3,
            enum_File = 4,
        };
        Array_uint16 value;
        uint8 null;
    }
    LogStorage;
    Property<Array_String> OtherLogStorageDescriptions;
    struct _VerbosityLevel
    {
        enum
        {
            enum_Minimum = 2,
            enum_Standard = 3,
            enum_Full = 4,
        };
        Array_uint16 value;
        uint8 null;
    }
    VerbosityLevel;
    Property<uint32> QueryTimeout;
    Property<boolean> NonDestructive;

    CIMPLE_CLASS(CIM_DiagnosticSettingData)
};

CIMPLE_NAMESPACE_END

#endif /* _cimple_CIM_DiagnosticSettingData_h */
