/*NOCHKSRC*/
//==============================================================================
//
// PLEASE DO NOT EDIT; THIS FILE WAS AUTOMATICALLY GENERATED BY GENCLASS 2.0.24
//
//==============================================================================

#include <cimple/Meta_Class.h>
#include <cimple/Meta_Property.h>
#include <cimple/Meta_Reference.h>
#include "CIM_Container.h"

CIMPLE_NAMESPACE_BEGIN

using namespace cimple;

extern const Meta_Repository __meta_repository_D1C632A09C56102581AE6FCCFC9FF5F6;

/*[1653]*/
extern const Meta_Reference
_CIM_Container_GroupComponent;

/*[1664]*/
const Meta_Reference
_CIM_Container_GroupComponent =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_REFERENCE|CIMPLE_FLAG_KEY|CIMPLE_FLAG_AGGREGATE,
    "GroupComponent",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    0, /* subscript */
    &CIM_PhysicalPackage::static_meta_class,
    CIMPLE_OFF(CIM_Container,GroupComponent)
};

/*[1653]*/
extern const Meta_Reference
_CIM_Container_PartComponent;

/*[1664]*/
const Meta_Reference
_CIM_Container_PartComponent =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_REFERENCE|CIMPLE_FLAG_KEY,
    "PartComponent",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    0, /* subscript */
    &CIM_PhysicalElement::static_meta_class,
    CIMPLE_OFF(CIM_Container,PartComponent)
};

/*[1568]*/
extern const Meta_Property
_CIM_Container_LocationWithinContainer;

/*[1591]*/
const Meta_Property
_CIM_Container_LocationWithinContainer =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_READ,
    "LocationWithinContainer",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    STRING,
    0, /* subscript */
    CIMPLE_OFF(CIM_Container,LocationWithinContainer),
    0, /* value */
};

/*[2291]*/
static Meta_Feature* _CIM_Container_MFA[] =
{
    (Meta_Feature*)(void*)&_CIM_Container_GroupComponent,
    (Meta_Feature*)(void*)&_CIM_Container_PartComponent,
    (Meta_Feature*)(void*)&_CIM_Container_LocationWithinContainer,
};

/*[2338]*/
static const Meta_Feature_Local _locals[] =
{
    {1},
    {1},
    {1},
};

/*[2358]*/
const Meta_Class CIM_Container::static_meta_class =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_ASSOCIATION|CIMPLE_FLAG_AGGREGATION,
    "CIM_Container",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _CIM_Container_MFA,
    CIMPLE_ARRAY_SIZE(_CIM_Container_MFA),
    sizeof(CIM_Container),
    _locals,
    &CIM_Component::static_meta_class,
    2, /* num_keys */
    &__meta_repository_D1C632A09C56102581AE6FCCFC9FF5F6,
};

CIMPLE_NAMESPACE_END

