

class SF_SoftwareIdentity : CIM_SoftwareIdentity {
};

class SF_ConcreteJob : CIM_ConcreteJob {
};

[Association]
class SF_InstalledSoftwareIdentity : CIM_InstalledSoftwareIdentity {
};

[Association]
class SF_ElementSoftwareIdentity : CIM_ElementSoftwareIdentity {
};


[Association]
class SF_BundleComponent : CIM_OrderedComponent {
};

class SF_ComputerSystem : CIM_ComputerSystem {
};

class SF_NICCard : CIM_Card {
};

class SF_PhysicalConnector : CIM_PhysicalConnector {
};

[Association]
class SF_ConnectorOnNIC : CIM_ConnectorOnPackage {
};

class SF_EthernetPort : CIM_EthernetPort {
};

class SF_PortController : CIM_PortController {
};

[Association]
class SF_SystemDevice : CIM_SystemDevice {
};

[Association]
class SF_ConnectorRealizesPort : CIM_Realizes {
};

class SF_LANEndpoint : CIM_LANEndpoint {
};

[Association]
class SF_NICSAPImplementation : CIM_DeviceSAPImplementation {
};

class SF_SoftwareInstallationService : CIM_SoftwareInstallationService {
};

class SF_SoftwareInstallationServiceCapabilities : CIM_SoftwareInstallationServiceCapabilities {
};

[Association]
class SF_ElementCapabilities : CIM_ElementCapabilities {
};

[Association]
class SF_ServiceAffectsElement : CIM_ServiceAffectsElement {
};

[Association]
class SF_HostedService : CIM_HostedService {
};

[Association]
class SF_ControlledBy : CIM_ControlledBy {
};

[Association]
class SF_HostedAccessPoint : CIM_HostedAccessPoint {
};

class SF_EnabledLogicalElementCapabilities : CIM_EnabledLogicalElementCapabilities {
};

class SF_RecordLog : CIM_RecordLog {
};

class SF_DiagnosticLog : CIM_DiagnosticLog {
};


class SF_LogEntry : CIM_LogEntry {
};

[Association]
class SF_LogManagesRecord : CIM_LogManagesRecord {
};

[Association]
class SF_UseOfLog : CIM_UseOfLog {
};






