//==============================================================================
//
// PLEASE DO NOT EDIT; THIS FILE WAS AUTOMATICALLY GENERATED BY GENCLASS 2.0.24
//
//==============================================================================

#include <cimple/cimple.h>
#include "repository.h"

CIMPLE_NAMESPACE_BEGIN

/*[2817]*/
static const Meta_Class* _meta_classes[] =
{
    &CIM_ManagedElement::static_meta_class,
    &CIM_ManagedSystemElement::static_meta_class,
    &CIM_LogicalElement::static_meta_class,
    &CIM_SoftwareIdentity::static_meta_class,
    &SF_SoftwareIdentity::static_meta_class,
    &CIM_Job::static_meta_class,
    &CIM_Error::static_meta_class,
    &CIM_ConcreteJob::static_meta_class,
    &SF_ConcreteJob::static_meta_class,
    &CIM_EnabledLogicalElement::static_meta_class,
    &CIM_System::static_meta_class,
    &CIM_InstalledSoftwareIdentity::static_meta_class,
    &SF_InstalledSoftwareIdentity::static_meta_class,
    &CIM_Component::static_meta_class,
    &CIM_OrderedComponent::static_meta_class,
    &SF_BundleComponent::static_meta_class,
    &CIM_ComputerSystem::static_meta_class,
    &SF_ComputerSystem::static_meta_class,
    &CIM_PhysicalElement::static_meta_class,
    &CIM_PhysicalPackage::static_meta_class,
    &CIM_PhysicalConnector::static_meta_class,
    &CIM_Card::static_meta_class,
    &SF_NICCard::static_meta_class,
    &SF_PhysicalConnector::static_meta_class,
    &CIM_Container::static_meta_class,
    &CIM_ConnectorOnPackage::static_meta_class,
    &SF_ConnectorOnNIC::static_meta_class,
    &CIM_LogicalDevice::static_meta_class,
    &CIM_LogicalPort::static_meta_class,
    &CIM_NetworkPort::static_meta_class,
    &CIM_EthernetPort::static_meta_class,
    &SF_EthernetPort::static_meta_class,
    &CIM_Controller::static_meta_class,
    &CIM_PortController::static_meta_class,
    &SF_PortController::static_meta_class,
    &CIM_SystemComponent::static_meta_class,
    &CIM_SystemDevice::static_meta_class,
    &SF_SystemDevice::static_meta_class,
    &CIM_Dependency::static_meta_class,
    &CIM_Realizes::static_meta_class,
    &SF_ConnectorRealizesPort::static_meta_class,
    &CIM_ServiceAccessPoint::static_meta_class,
    &CIM_ProtocolEndpoint::static_meta_class,
    &CIM_LANEndpoint::static_meta_class,
    &SF_LANEndpoint::static_meta_class,
};

static const size_t _num_meta_classes = CIMPLE_ARRAY_SIZE(_meta_classes);

extern const Meta_Repository __meta_repository_6CA0219685691FADA8733C94FE01BD97;

/*[2844]*/
const Meta_Repository __meta_repository_6CA0219685691FADA8733C94FE01BD97 =
{
    _meta_classes,
    _num_meta_classes,
};

CIMPLE_NAMESPACE_END
