// Generated by genprov 2.0.24
#ifndef _SF_ConnectorOnNIC_Provider_h
#define _SF_ConnectorOnNIC_Provider_h

#include <cimple/cimple.h>
#include "SF_ConnectorOnNIC.h"
#include "sf_platform.h"

CIMPLE_NAMESPACE_BEGIN

class SF_ConnectorOnNIC_Provider
{
    class ConstEnum : public solarflare::ConstPortEnumerator {
        Enum_Instances_Handler<SF_ConnectorOnNIC>* handler;
    public:
        ConstEnum(Enum_Instances_Handler<SF_ConnectorOnNIC>* h) :
            handler(h) {};
        virtual bool process(const solarflare::Port& e);
    };
public:

    typedef SF_ConnectorOnNIC Class;

    SF_ConnectorOnNIC_Provider();

    ~SF_ConnectorOnNIC_Provider();

    Load_Status load();

    Unload_Status unload();

    Get_Instance_Status get_instance(
        const SF_ConnectorOnNIC* model,
        SF_ConnectorOnNIC*& instance);

    Enum_Instances_Status enum_instances(
        const SF_ConnectorOnNIC* model,
        Enum_Instances_Handler<SF_ConnectorOnNIC>* handler);

    Create_Instance_Status create_instance(
        SF_ConnectorOnNIC* instance);

    Delete_Instance_Status delete_instance(
        const SF_ConnectorOnNIC* instance);

    Modify_Instance_Status modify_instance(
        const SF_ConnectorOnNIC* model,
        const SF_ConnectorOnNIC* instance);

    Enum_Associator_Names_Status enum_associator_names(
        const Instance* instance,
        const String& result_class,
        const String& role,
        const String& result_role,
        Enum_Associator_Names_Handler<Instance>* handler);

    Enum_Associators_Status enum_associators(
        const Instance* instance,
        const String& result_class,
        const String& role,
        const String& result_role,
        Enum_Associators_Handler<Instance>* handler);

    Enum_References_Status enum_references(
        const Instance* instance,
        const SF_ConnectorOnNIC* model,
        const String& role,
        Enum_References_Handler<SF_ConnectorOnNIC>* handler);

    /*@END@*/
};

CIMPLE_NAMESPACE_END

#endif /* _SF_ConnectorOnNIC_Provider_h */
