// Generated by genprov 2.0.24
#ifndef _SF_ConnectorRealizesPort_Provider_h
#define _SF_ConnectorRealizesPort_Provider_h

#include <cimple/cimple.h>
#include "SF_ConnectorRealizesPort.h"
#include "sf_platform.h"

CIMPLE_NAMESPACE_BEGIN

class SF_ConnectorRealizesPort_Provider
{
    class InterfaceEnum : public solarflare::ConstElementEnumerator {
        Enum_Instances_Handler<SF_ConnectorRealizesPort>* handler;
    public:
        InterfaceEnum(Enum_Instances_Handler<SF_ConnectorRealizesPort>* h) :
            handler(h) {}
        virtual bool process(const solarflare::SystemElement& se);
    };
public:

    typedef SF_ConnectorRealizesPort Class;

    SF_ConnectorRealizesPort_Provider();

    ~SF_ConnectorRealizesPort_Provider();

    Load_Status load();

    Unload_Status unload();

    Get_Instance_Status get_instance(
        const SF_ConnectorRealizesPort* model,
        SF_ConnectorRealizesPort*& instance);

    Enum_Instances_Status enum_instances(
        const SF_ConnectorRealizesPort* model,
        Enum_Instances_Handler<SF_ConnectorRealizesPort>* handler);

    Create_Instance_Status create_instance(
        SF_ConnectorRealizesPort* instance);

    Delete_Instance_Status delete_instance(
        const SF_ConnectorRealizesPort* instance);

    Modify_Instance_Status modify_instance(
        const SF_ConnectorRealizesPort* model,
        const SF_ConnectorRealizesPort* instance);

    Enum_Associator_Names_Status enum_associator_names(
        const Instance* instance,
        const String& result_class,
        const String& role,
        const String& result_role,
        Enum_Associator_Names_Handler<Instance>* handler);

    Enum_Associators_Status enum_associators(
        const Instance* instance,
        const String& result_class,
        const String& role,
        const String& result_role,
        Enum_Associators_Handler<Instance>* handler);

    Enum_References_Status enum_references(
        const Instance* instance,
        const SF_ConnectorRealizesPort* model,
        const String& role,
        Enum_References_Handler<SF_ConnectorRealizesPort>* handler);

    /*@END@*/
};

CIMPLE_NAMESPACE_END

#endif /* _SF_ConnectorRealizesPort_Provider_h */
