/*NOCHKSRC*/
//==============================================================================
//
// PLEASE DO NOT EDIT; THIS FILE WAS AUTOMATICALLY GENERATED BY GENCLASS 2.0.24
//
//==============================================================================

#include <cimple/Meta_Class.h>
#include <cimple/Meta_Property.h>
#include <cimple/Meta_Reference.h>
#include "SF_DiagnosticSettingData.h"

CIMPLE_NAMESPACE_BEGIN

using namespace cimple;

extern const Meta_Repository __meta_repository_0DDA66E0FF471BAB95C366A9360C9285;

/*[1568]*/
extern const Meta_Property
_CIM_SettingData_InstanceID;

/*[1568]*/
extern const Meta_Property
_CIM_ManagedElement_Caption;

/*[1568]*/
extern const Meta_Property
_CIM_ManagedElement_Description;

/*[1568]*/
extern const Meta_Property
_CIM_SettingData_ElementName;

/*[1568]*/
extern const Meta_Property
_CIM_ManagedElement_Generation;

/*[1568]*/
extern const Meta_Property
_CIM_SettingData_ConfigurationName;

/*[1568]*/
extern const Meta_Property
_CIM_SettingData_ChangeableType;

/*[1568]*/
extern const Meta_Property
_CIM_DiagnosticSettingData_HaltOnError;

/*[1568]*/
extern const Meta_Property
_CIM_DiagnosticSettingData_QuickMode;

/*[1568]*/
extern const Meta_Property
_CIM_DiagnosticSettingData_PercentOfTestCoverage;

/*[1568]*/
extern const Meta_Property
_CIM_DiagnosticSettingData_LoopControlParameter;

/*[1568]*/
extern const Meta_Property
_CIM_DiagnosticSettingData_LoopControl;

/*[1568]*/
extern const Meta_Property
_CIM_DiagnosticSettingData_OtherLoopControlDescriptions;

/*[1568]*/
extern const Meta_Property
_CIM_DiagnosticSettingData_ResultPersistence;

/*[1568]*/
extern const Meta_Property
_CIM_DiagnosticSettingData_LogOptions;

/*[1568]*/
extern const Meta_Property
_CIM_DiagnosticSettingData_OtherLogOptionsDescriptions;

/*[1568]*/
extern const Meta_Property
_CIM_DiagnosticSettingData_LogStorage;

/*[1568]*/
extern const Meta_Property
_CIM_DiagnosticSettingData_OtherLogStorageDescriptions;

/*[1568]*/
extern const Meta_Property
_CIM_DiagnosticSettingData_VerbosityLevel;

/*[1568]*/
extern const Meta_Property
_CIM_DiagnosticSettingData_QueryTimeout;

/*[1568]*/
extern const Meta_Property
_CIM_DiagnosticSettingData_NonDestructive;

/*[2291]*/
static Meta_Feature* _SF_DiagnosticSettingData_MFA[] =
{
    (Meta_Feature*)(void*)&_CIM_SettingData_InstanceID,
    (Meta_Feature*)(void*)&_CIM_ManagedElement_Caption,
    (Meta_Feature*)(void*)&_CIM_ManagedElement_Description,
    (Meta_Feature*)(void*)&_CIM_SettingData_ElementName,
    (Meta_Feature*)(void*)&_CIM_ManagedElement_Generation,
    (Meta_Feature*)(void*)&_CIM_SettingData_ConfigurationName,
    (Meta_Feature*)(void*)&_CIM_SettingData_ChangeableType,
    (Meta_Feature*)(void*)&_CIM_DiagnosticSettingData_HaltOnError,
    (Meta_Feature*)(void*)&_CIM_DiagnosticSettingData_QuickMode,
    (Meta_Feature*)(void*)&_CIM_DiagnosticSettingData_PercentOfTestCoverage,
    (Meta_Feature*)(void*)&_CIM_DiagnosticSettingData_LoopControlParameter,
    (Meta_Feature*)(void*)&_CIM_DiagnosticSettingData_LoopControl,
    (Meta_Feature*)(void*)&_CIM_DiagnosticSettingData_OtherLoopControlDescriptions,
    (Meta_Feature*)(void*)&_CIM_DiagnosticSettingData_ResultPersistence,
    (Meta_Feature*)(void*)&_CIM_DiagnosticSettingData_LogOptions,
    (Meta_Feature*)(void*)&_CIM_DiagnosticSettingData_OtherLogOptionsDescriptions,
    (Meta_Feature*)(void*)&_CIM_DiagnosticSettingData_LogStorage,
    (Meta_Feature*)(void*)&_CIM_DiagnosticSettingData_OtherLogStorageDescriptions,
    (Meta_Feature*)(void*)&_CIM_DiagnosticSettingData_VerbosityLevel,
    (Meta_Feature*)(void*)&_CIM_DiagnosticSettingData_QueryTimeout,
    (Meta_Feature*)(void*)&_CIM_DiagnosticSettingData_NonDestructive,
};

/*[2338]*/
static const Meta_Feature_Local _locals[] =
{
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
};

/*[2358]*/
const Meta_Class SF_DiagnosticSettingData::static_meta_class =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_CLASS,
    "SF_DiagnosticSettingData",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _SF_DiagnosticSettingData_MFA,
    CIMPLE_ARRAY_SIZE(_SF_DiagnosticSettingData_MFA),
    sizeof(SF_DiagnosticSettingData),
    _locals,
    &CIM_DiagnosticSettingData::static_meta_class,
    1, /* num_keys */
    &__meta_repository_0DDA66E0FF471BAB95C366A9360C9285,
};

CIMPLE_NAMESPACE_END

