/*NOCHKSRC*/
//==============================================================================
//
// PLEASE DO NOT EDIT; THIS FILE WAS AUTOMATICALLY GENERATED BY GENCLASS 2.0.24
//
//==============================================================================

#include <cimple/Meta_Class.h>
#include <cimple/Meta_Property.h>
#include <cimple/Meta_Reference.h>
#include "SF_DiagnosticServiceCapabilities.h"

CIMPLE_NAMESPACE_BEGIN

using namespace cimple;

extern const Meta_Repository __meta_repository_480038F9449B17AC9E2210119CF38AF2;

/*[1568]*/
extern const Meta_Property
_CIM_Capabilities_InstanceID;

/*[1568]*/
extern const Meta_Property
_CIM_ManagedElement_Caption;

/*[1568]*/
extern const Meta_Property
_CIM_ManagedElement_Description;

/*[1568]*/
extern const Meta_Property
_CIM_Capabilities_ElementName;

/*[1568]*/
extern const Meta_Property
_CIM_DiagnosticServiceCapabilities_SupportedServiceModes;

/*[1568]*/
extern const Meta_Property
_CIM_DiagnosticServiceCapabilities_OtherSupportedServiceModesDescriptions;

/*[1568]*/
extern const Meta_Property
_CIM_DiagnosticServiceCapabilities_SupportedLoopControl;

/*[1568]*/
extern const Meta_Property
_CIM_DiagnosticServiceCapabilities_OtherSupportedLoopControlDescriptions;

/*[1568]*/
extern const Meta_Property
_CIM_DiagnosticServiceCapabilities_SupportedLogOptions;

/*[1568]*/
extern const Meta_Property
_CIM_DiagnosticServiceCapabilities_OtherSupportedLogOptionsDescriptions;

/*[1568]*/
extern const Meta_Property
_CIM_DiagnosticServiceCapabilities_SupportedLogStorage;

/*[1568]*/
extern const Meta_Property
_CIM_DiagnosticServiceCapabilities_OtherSupportedLogStorageDescriptions;

/*[1568]*/
extern const Meta_Property
_CIM_DiagnosticServiceCapabilities_SupportedExecutionControls;

/*[1568]*/
extern const Meta_Property
_CIM_DiagnosticServiceCapabilities_OtherSupportedExecutionControlsDescriptions;

/*[1568]*/
extern const Meta_Property
_CIM_DiagnosticServiceCapabilities_SupportedTestWarnings;

/*[2291]*/
static Meta_Feature* _SF_DiagnosticServiceCapabilities_MFA[] =
{
    (Meta_Feature*)(void*)&_CIM_Capabilities_InstanceID,
    (Meta_Feature*)(void*)&_CIM_ManagedElement_Caption,
    (Meta_Feature*)(void*)&_CIM_ManagedElement_Description,
    (Meta_Feature*)(void*)&_CIM_Capabilities_ElementName,
    (Meta_Feature*)(void*)&_CIM_DiagnosticServiceCapabilities_SupportedServiceModes,
    (Meta_Feature*)(void*)&_CIM_DiagnosticServiceCapabilities_OtherSupportedServiceModesDescriptions,
    (Meta_Feature*)(void*)&_CIM_DiagnosticServiceCapabilities_SupportedLoopControl,
    (Meta_Feature*)(void*)&_CIM_DiagnosticServiceCapabilities_OtherSupportedLoopControlDescriptions,
    (Meta_Feature*)(void*)&_CIM_DiagnosticServiceCapabilities_SupportedLogOptions,
    (Meta_Feature*)(void*)&_CIM_DiagnosticServiceCapabilities_OtherSupportedLogOptionsDescriptions,
    (Meta_Feature*)(void*)&_CIM_DiagnosticServiceCapabilities_SupportedLogStorage,
    (Meta_Feature*)(void*)&_CIM_DiagnosticServiceCapabilities_OtherSupportedLogStorageDescriptions,
    (Meta_Feature*)(void*)&_CIM_DiagnosticServiceCapabilities_SupportedExecutionControls,
    (Meta_Feature*)(void*)&_CIM_DiagnosticServiceCapabilities_OtherSupportedExecutionControlsDescriptions,
    (Meta_Feature*)(void*)&_CIM_DiagnosticServiceCapabilities_SupportedTestWarnings,
};

/*[2338]*/
static const Meta_Feature_Local _locals[] =
{
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
};

/*[2358]*/
const Meta_Class SF_DiagnosticServiceCapabilities::static_meta_class =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_CLASS,
    "SF_DiagnosticServiceCapabilities",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _SF_DiagnosticServiceCapabilities_MFA,
    CIMPLE_ARRAY_SIZE(_SF_DiagnosticServiceCapabilities_MFA),
    sizeof(SF_DiagnosticServiceCapabilities),
    _locals,
    &CIM_DiagnosticServiceCapabilities::static_meta_class,
    1, /* num_keys */
    &__meta_repository_480038F9449B17AC9E2210119CF38AF2,
};

CIMPLE_NAMESPACE_END

