// Generated by genprov 2.0.24
#ifndef _SF_ElementConformsToProfile_Provider_h
#define _SF_ElementConformsToProfile_Provider_h

#include <cimple/cimple.h>
#include "SF_ElementConformsToProfile.h"
#include "SF_RegisteredProfile_Provider.h"
#include "sf_platform.h"

CIMPLE_NAMESPACE_BEGIN

class SF_ElementConformsToProfile_Provider
{
    static const char *const implementationNamespace;
    static const char *const interopNamespace;

    class EnumAll : public solarflare::ConstSoftwareEnumerator,
                    public solarflare::ConstNICEnumerator,
                    public solarflare::ConstInterfaceEnumerator,
                    public solarflare::ConstPortEnumerator,
                    public solarflare::ConstDiagnosticEnumerator
    {
        Enum_Instances_Handler<SF_ElementConformsToProfile>* handler;
    public:
        EnumAll(Enum_Instances_Handler<SF_ElementConformsToProfile>* h) :
            handler(h) {}
        virtual bool process(const solarflare::SWElement& sw);
        virtual bool process(const solarflare::NIC& nic);
        virtual bool process(const solarflare::Port& port);
        virtual bool process(const solarflare::Interface& intf);
        virtual bool process(const solarflare::Diagnostic& diag);
    };

    static SF_ElementConformsToProfile *makeLink(const SF_RegisteredProfile_Provider::DMTFProfileInfo &profile,
                                                 Instance *obj);
        
public:

    typedef SF_ElementConformsToProfile Class;

    SF_ElementConformsToProfile_Provider();

    ~SF_ElementConformsToProfile_Provider();

    Load_Status load();

    Unload_Status unload();

    Get_Instance_Status get_instance(
        const SF_ElementConformsToProfile* model,
        SF_ElementConformsToProfile*& instance);

    Enum_Instances_Status enum_instances(
        const SF_ElementConformsToProfile* model,
        Enum_Instances_Handler<SF_ElementConformsToProfile>* handler);

    Create_Instance_Status create_instance(
        SF_ElementConformsToProfile* instance);

    Delete_Instance_Status delete_instance(
        const SF_ElementConformsToProfile* instance);

    Modify_Instance_Status modify_instance(
        const SF_ElementConformsToProfile* model,
        const SF_ElementConformsToProfile* instance);

    Enum_Associator_Names_Status enum_associator_names(
        const Instance* instance,
        const String& result_class,
        const String& role,
        const String& result_role,
        Enum_Associator_Names_Handler<Instance>* handler);

    Enum_Associators_Status enum_associators(
        const Instance* instance,
        const String& result_class,
        const String& role,
        const String& result_role,
        Enum_Associators_Handler<Instance>* handler);

    Enum_References_Status enum_references(
        const Instance* instance,
        const SF_ElementConformsToProfile* model,
        const String& role,
        Enum_References_Handler<SF_ElementConformsToProfile>* handler);

    /*@END@*/
};

CIMPLE_NAMESPACE_END

#endif /* _SF_ElementConformsToProfile_Provider_h */
