// Generated by genprov 2.0.24
#ifndef _SF_EnabledLogicalElementCapabilities_Provider_h
#define _SF_EnabledLogicalElementCapabilities_Provider_h

#include <cimple/cimple.h>
#include "SF_EnabledLogicalElementCapabilities.h"
#include "sf_platform.h"

CIMPLE_NAMESPACE_BEGIN

class SF_EnabledLogicalElementCapabilities_Provider
{
    class NICIntfEnum : public solarflare::ConstNICEnumerator,
                        public solarflare::ConstInterfaceEnumerator
    {
        Enum_Instances_Handler<SF_EnabledLogicalElementCapabilities>* handler;
    public:
        NICIntfEnum(Enum_Instances_Handler<SF_EnabledLogicalElementCapabilities>* h) :
            handler(h) {}
        virtual bool process(const solarflare::NIC& nic);
        virtual bool process(const solarflare::Interface& intf);
    };
    static SF_EnabledLogicalElementCapabilities *makeInstance(const solarflare::SystemElement& intf, 
                                                              const char *nameSuffix,
                                                              bool manageable);
public:

    static SF_EnabledLogicalElementCapabilities *makeReference(const solarflare::SystemElement& intf, 
                                                               const char *nameSuffix);
    

    typedef SF_EnabledLogicalElementCapabilities Class;

    SF_EnabledLogicalElementCapabilities_Provider();

    ~SF_EnabledLogicalElementCapabilities_Provider();

    Load_Status load();

    Unload_Status unload();

    Get_Instance_Status get_instance(
        const SF_EnabledLogicalElementCapabilities* model,
        SF_EnabledLogicalElementCapabilities*& instance);

    Enum_Instances_Status enum_instances(
        const SF_EnabledLogicalElementCapabilities* model,
        Enum_Instances_Handler<SF_EnabledLogicalElementCapabilities>* handler);

    Create_Instance_Status create_instance(
        SF_EnabledLogicalElementCapabilities* instance);

    Delete_Instance_Status delete_instance(
        const SF_EnabledLogicalElementCapabilities* instance);

    Modify_Instance_Status modify_instance(
        const SF_EnabledLogicalElementCapabilities* model,
        const SF_EnabledLogicalElementCapabilities* instance);

    /*@END@*/
};

CIMPLE_NAMESPACE_END

#endif /* _SF_EnabledLogicalElementCapabilities_Provider_h */
