/*NOCHKSRC*/
//==============================================================================
//
// PLEASE DO NOT EDIT; THIS FILE WAS AUTOMATICALLY GENERATED BY GENCLASS 2.0.24
//
//==============================================================================

#ifndef _cimple_SF_ElementCapabilities_h
#define _cimple_SF_ElementCapabilities_h

#include <cimple/cimple.h>
#include "CIM_ElementCapabilities.h"

CIMPLE_NAMESPACE_BEGIN

// SF_ElementCapabilities keys:

/*[1194]*/
class SF_ElementCapabilities : public Instance
{
public:
    // CIM_ElementCapabilities features:
    CIM_ManagedElement* ManagedElement;
    CIM_Capabilities* Capabilities;
    struct _Characteristics
    {
        enum
        {
            enum_Default = 2,
            enum_Current = 3,
            enum_DMTF_Reserved = 0,
            enum_Vendor_Specific = 32768,
        };
        Array_uint16 value;
        uint8 null;
    }
    Characteristics;

    // SF_ElementCapabilities features:

    CIMPLE_CLASS(SF_ElementCapabilities)
};

CIMPLE_NAMESPACE_END

#endif /* _cimple_SF_ElementCapabilities_h */
