// Generated by genprov 2.0.24
#include "SF_HostedAccessPoint_Provider.h"
#include "SF_ComputerSystem_Provider.h"
#include "SF_LANEndpoint_Provider.h"
#include "sf_provider.h"

CIMPLE_NAMESPACE_BEGIN

bool 
SF_HostedAccessPoint_Provider::InterfaceEnum::process(const solarflare::SystemElement& se)
{
    const solarflare::Interface& intf = static_cast<const solarflare::Interface&>(se);
    SF_HostedAccessPoint *link = SF_HostedAccessPoint::create(true);
    link->Antecedent = solarflare::CIMHelper::systemRef();
    link->Dependent = cast<CIM_ServiceAccessPoint *>(intf.cimReference(SF_LANEndpoint::static_meta_class));
    handler->handle(link);
    return true;
}


SF_HostedAccessPoint_Provider::SF_HostedAccessPoint_Provider()
{
}

SF_HostedAccessPoint_Provider::~SF_HostedAccessPoint_Provider()
{
}

Load_Status SF_HostedAccessPoint_Provider::load()
{
    solarflare::System::target.initialize();
    return LOAD_OK;
}

Unload_Status SF_HostedAccessPoint_Provider::unload()
{
    return UNLOAD_OK;
}

Get_Instance_Status SF_HostedAccessPoint_Provider::get_instance(
    const SF_HostedAccessPoint* model,
    SF_HostedAccessPoint*& instance)
{
    return GET_INSTANCE_UNSUPPORTED;
}

Enum_Instances_Status SF_HostedAccessPoint_Provider::enum_instances(
    const SF_HostedAccessPoint* model,
    Enum_Instances_Handler<SF_HostedAccessPoint>* handler)
{
    InterfaceEnum endpoints(handler);
    solarflare::System::target.forAllInterfaces(endpoints);
    return ENUM_INSTANCES_OK;
}

Create_Instance_Status SF_HostedAccessPoint_Provider::create_instance(
    SF_HostedAccessPoint* instance)
{
    return CREATE_INSTANCE_UNSUPPORTED;
}

Delete_Instance_Status SF_HostedAccessPoint_Provider::delete_instance(
    const SF_HostedAccessPoint* instance)
{
    return DELETE_INSTANCE_UNSUPPORTED;
}

Modify_Instance_Status SF_HostedAccessPoint_Provider::modify_instance(
    const SF_HostedAccessPoint* model,
    const SF_HostedAccessPoint* instance)
{
    return MODIFY_INSTANCE_UNSUPPORTED;
}

Enum_Associator_Names_Status SF_HostedAccessPoint_Provider::enum_associator_names(
    const Instance* instance,
    const String& result_class,
    const String& role,
    const String& result_role,
    Enum_Associator_Names_Handler<Instance>* handler)
{
    return ENUM_ASSOCIATOR_NAMES_UNSUPPORTED;
}

Enum_Associators_Status SF_HostedAccessPoint_Provider::enum_associators(
    const Instance* instance,
    const String& result_class,
    const String& role,
    const String& result_role,
    Enum_Associators_Handler<Instance>* handler)
{
    return ENUM_ASSOCIATORS_UNSUPPORTED;
}

Enum_References_Status SF_HostedAccessPoint_Provider::enum_references(
    const Instance* instance,
    const SF_HostedAccessPoint* model,
    const String& role,
    Enum_References_Handler<SF_HostedAccessPoint>* handler)
{
    return ENUM_REFERENCES_UNSUPPORTED;
}

/*@END@*/

CIMPLE_NAMESPACE_END
