/*NOCHKSRC*/
//==============================================================================
//
// PLEASE DO NOT EDIT; THIS FILE WAS AUTOMATICALLY GENERATED BY GENCLASS 2.0.24
//
//==============================================================================

#ifndef _cimple_SF_LogEntry_h
#define _cimple_SF_LogEntry_h

#include <cimple/cimple.h>
#include "CIM_LogEntry.h"

CIMPLE_NAMESPACE_BEGIN

// SF_LogEntry keys:
//     InstanceID

/*[1194]*/
class SF_LogEntry : public Instance
{
public:
    // CIM_ManagedElement features:
    Property<String> InstanceID;
    Property<String> Caption;
    Property<String> Description;
    Property<String> ElementName;

    // CIM_RecordForLog features:
    Property<String> RecordFormat;
    Property<String> RecordData;
    Property<String> Locale;
    struct _PerceivedSeverity
    {
        enum
        {
            enum_Unknown = 0,
            enum_Other = 1,
            enum_Information = 2,
            enum_Degraded_Warning = 3,
            enum_Minor = 4,
            enum_Major = 5,
            enum_Critical = 6,
            enum_Fatal_NonRecoverable = 7,
        };
        uint16 value;
        uint8 null;
    }
    PerceivedSeverity;

    // CIM_LogEntry features:
    Property<String> LogInstanceID;
    Property<String> LogName;
    Property<String> RecordID;
    Property<Datetime> CreationTimeStamp;
    Property<String> MessageID;
    Property<String> Message;
    Property<Array_String> MessageArguments;
    Property<String> OwningEntity;

    // SF_LogEntry features:

    CIMPLE_CLASS(SF_LogEntry)
};

CIMPLE_NAMESPACE_END

#endif /* _cimple_SF_LogEntry_h */
