// Generated by genprov 2.0.24
#ifndef _SF_LogEntry_Provider_h
#define _SF_LogEntry_Provider_h

#include <cimple/cimple.h>
#include "SF_LogEntry.h"
#include "sf_logging.h"

CIMPLE_NAMESPACE_BEGIN

class SF_LogEntry_Provider
{
public:

    typedef SF_LogEntry Class;

    SF_LogEntry_Provider();

    ~SF_LogEntry_Provider();

    Load_Status load();

    Unload_Status unload();

    Get_Instance_Status get_instance(
        const SF_LogEntry* model,
        SF_LogEntry*& instance);

    Enum_Instances_Status enum_instances(
        const SF_LogEntry* model,
        Enum_Instances_Handler<SF_LogEntry>* handler);

    Create_Instance_Status create_instance(
        SF_LogEntry* instance);

    Delete_Instance_Status delete_instance(
        const SF_LogEntry* instance);

    Modify_Instance_Status modify_instance(
        const SF_LogEntry* model,
        const SF_LogEntry* instance);

    /*@END@*/
};

CIMPLE_NAMESPACE_END

#endif /* _SF_LogEntry_Provider_h */
