/*NOCHKSRC*/
//==============================================================================
//
// PLEASE DO NOT EDIT; THIS FILE WAS AUTOMATICALLY GENERATED BY GENCLASS 2.0.24
//
//==============================================================================

#include <cimple/Meta_Class.h>
#include <cimple/Meta_Property.h>
#include <cimple/Meta_Reference.h>
#include "SF_NICCard.h"

CIMPLE_NAMESPACE_BEGIN

using namespace cimple;

extern const Meta_Repository __meta_repository_CCA3FB4C49C51F2D868FF3E04426D671;

/*[1568]*/
extern const Meta_Property
_CIM_ManagedElement_InstanceID;

/*[1568]*/
extern const Meta_Property
_CIM_ManagedElement_Caption;

/*[1568]*/
extern const Meta_Property
_CIM_PhysicalElement_Description;

/*[1568]*/
extern const Meta_Property
_CIM_PhysicalElement_ElementName;

/*[1568]*/
extern const Meta_Property
_CIM_ManagedSystemElement_InstallDate;

/*[1568]*/
extern const Meta_Property
_CIM_ManagedSystemElement_Name;

/*[1568]*/
extern const Meta_Property
_CIM_ManagedSystemElement_OperationalStatus;

/*[1568]*/
extern const Meta_Property
_CIM_ManagedSystemElement_StatusDescriptions;

/*[1568]*/
extern const Meta_Property
_CIM_ManagedSystemElement_Status;

/*[1568]*/
extern const Meta_Property
_CIM_ManagedSystemElement_HealthState;

/*[1568]*/
extern const Meta_Property
_CIM_ManagedSystemElement_CommunicationStatus;

/*[1568]*/
extern const Meta_Property
_CIM_ManagedSystemElement_DetailedStatus;

/*[1568]*/
extern const Meta_Property
_CIM_ManagedSystemElement_OperatingStatus;

/*[1568]*/
extern const Meta_Property
_CIM_ManagedSystemElement_PrimaryStatus;

/*[1568]*/
extern const Meta_Property
_CIM_PhysicalElement_Tag;

/*[1568]*/
extern const Meta_Property
_CIM_PhysicalElement_CreationClassName;

/*[1568]*/
extern const Meta_Property
_CIM_PhysicalElement_Manufacturer;

/*[1568]*/
extern const Meta_Property
_CIM_PhysicalElement_Model;

/*[1568]*/
extern const Meta_Property
_CIM_PhysicalElement_SKU;

/*[1568]*/
extern const Meta_Property
_CIM_PhysicalElement_SerialNumber;

/*[1568]*/
extern const Meta_Property
_CIM_PhysicalElement_Version;

/*[1568]*/
extern const Meta_Property
_CIM_PhysicalElement_PartNumber;

/*[1568]*/
extern const Meta_Property
_CIM_PhysicalElement_OtherIdentifyingInfo;

/*[1568]*/
extern const Meta_Property
_CIM_PhysicalElement_PoweredOn;

/*[1568]*/
extern const Meta_Property
_CIM_PhysicalElement_ManufactureDate;

/*[1568]*/
extern const Meta_Property
_CIM_PhysicalElement_VendorEquipmentType;

/*[1568]*/
extern const Meta_Property
_CIM_PhysicalElement_UserTracking;

/*[1568]*/
extern const Meta_Property
_CIM_PhysicalElement_CanBeFRUed;

/*[1568]*/
extern const Meta_Property
_CIM_PhysicalPackage_RemovalConditions;

/*[1568]*/
extern const Meta_Property
_CIM_PhysicalPackage_Removable;

/*[1568]*/
extern const Meta_Property
_CIM_PhysicalPackage_Replaceable;

/*[1568]*/
extern const Meta_Property
_CIM_PhysicalPackage_HotSwappable;

/*[1568]*/
extern const Meta_Property
_CIM_PhysicalPackage_Height;

/*[1568]*/
extern const Meta_Property
_CIM_PhysicalPackage_Depth;

/*[1568]*/
extern const Meta_Property
_CIM_PhysicalPackage_Width;

/*[1568]*/
extern const Meta_Property
_CIM_PhysicalPackage_Weight;

/*[1568]*/
extern const Meta_Property
_CIM_PhysicalPackage_PackageType;

/*[1568]*/
extern const Meta_Property
_CIM_PhysicalPackage_OtherPackageType;

/*[1568]*/
extern const Meta_Property
_CIM_PhysicalPackage_VendorCompatibilityStrings;

/*[1568]*/
extern const Meta_Property
_CIM_Card_HostingBoard;

/*[1568]*/
extern const Meta_Property
_CIM_Card_SlotLayout;

/*[1568]*/
extern const Meta_Property
_CIM_Card_RequiresDaughterBoard;

/*[1568]*/
extern const Meta_Property
_CIM_Card_SpecialRequirements;

/*[1568]*/
extern const Meta_Property
_CIM_Card_RequirementsDescription;

/*[1568]*/
extern const Meta_Property
_CIM_Card_OperatingVoltages;

/*[2291]*/
static Meta_Feature* _SF_NICCard_MFA[] =
{
    (Meta_Feature*)(void*)&_CIM_ManagedElement_InstanceID,
    (Meta_Feature*)(void*)&_CIM_ManagedElement_Caption,
    (Meta_Feature*)(void*)&_CIM_PhysicalElement_Description,
    (Meta_Feature*)(void*)&_CIM_PhysicalElement_ElementName,
    (Meta_Feature*)(void*)&_CIM_ManagedSystemElement_InstallDate,
    (Meta_Feature*)(void*)&_CIM_ManagedSystemElement_Name,
    (Meta_Feature*)(void*)&_CIM_ManagedSystemElement_OperationalStatus,
    (Meta_Feature*)(void*)&_CIM_ManagedSystemElement_StatusDescriptions,
    (Meta_Feature*)(void*)&_CIM_ManagedSystemElement_Status,
    (Meta_Feature*)(void*)&_CIM_ManagedSystemElement_HealthState,
    (Meta_Feature*)(void*)&_CIM_ManagedSystemElement_CommunicationStatus,
    (Meta_Feature*)(void*)&_CIM_ManagedSystemElement_DetailedStatus,
    (Meta_Feature*)(void*)&_CIM_ManagedSystemElement_OperatingStatus,
    (Meta_Feature*)(void*)&_CIM_ManagedSystemElement_PrimaryStatus,
    (Meta_Feature*)(void*)&_CIM_PhysicalElement_Tag,
    (Meta_Feature*)(void*)&_CIM_PhysicalElement_CreationClassName,
    (Meta_Feature*)(void*)&_CIM_PhysicalElement_Manufacturer,
    (Meta_Feature*)(void*)&_CIM_PhysicalElement_Model,
    (Meta_Feature*)(void*)&_CIM_PhysicalElement_SKU,
    (Meta_Feature*)(void*)&_CIM_PhysicalElement_SerialNumber,
    (Meta_Feature*)(void*)&_CIM_PhysicalElement_Version,
    (Meta_Feature*)(void*)&_CIM_PhysicalElement_PartNumber,
    (Meta_Feature*)(void*)&_CIM_PhysicalElement_OtherIdentifyingInfo,
    (Meta_Feature*)(void*)&_CIM_PhysicalElement_PoweredOn,
    (Meta_Feature*)(void*)&_CIM_PhysicalElement_ManufactureDate,
    (Meta_Feature*)(void*)&_CIM_PhysicalElement_VendorEquipmentType,
    (Meta_Feature*)(void*)&_CIM_PhysicalElement_UserTracking,
    (Meta_Feature*)(void*)&_CIM_PhysicalElement_CanBeFRUed,
    (Meta_Feature*)(void*)&_CIM_PhysicalPackage_RemovalConditions,
    (Meta_Feature*)(void*)&_CIM_PhysicalPackage_Removable,
    (Meta_Feature*)(void*)&_CIM_PhysicalPackage_Replaceable,
    (Meta_Feature*)(void*)&_CIM_PhysicalPackage_HotSwappable,
    (Meta_Feature*)(void*)&_CIM_PhysicalPackage_Height,
    (Meta_Feature*)(void*)&_CIM_PhysicalPackage_Depth,
    (Meta_Feature*)(void*)&_CIM_PhysicalPackage_Width,
    (Meta_Feature*)(void*)&_CIM_PhysicalPackage_Weight,
    (Meta_Feature*)(void*)&_CIM_PhysicalPackage_PackageType,
    (Meta_Feature*)(void*)&_CIM_PhysicalPackage_OtherPackageType,
    (Meta_Feature*)(void*)&_CIM_PhysicalPackage_VendorCompatibilityStrings,
    (Meta_Feature*)(void*)&CIM_PhysicalPackage_IsCompatible_method::static_meta_class,
    (Meta_Feature*)(void*)&_CIM_Card_HostingBoard,
    (Meta_Feature*)(void*)&_CIM_Card_SlotLayout,
    (Meta_Feature*)(void*)&_CIM_Card_RequiresDaughterBoard,
    (Meta_Feature*)(void*)&_CIM_Card_SpecialRequirements,
    (Meta_Feature*)(void*)&_CIM_Card_RequirementsDescription,
    (Meta_Feature*)(void*)&_CIM_Card_OperatingVoltages,
    (Meta_Feature*)(void*)&CIM_Card_ConnectorPower_method::static_meta_class,
};

/*[2338]*/
static const Meta_Feature_Local _locals[] =
{
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
};

/*[2358]*/
const Meta_Class SF_NICCard::static_meta_class =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_CLASS,
    "SF_NICCard",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _SF_NICCard_MFA,
    CIMPLE_ARRAY_SIZE(_SF_NICCard_MFA),
    sizeof(SF_NICCard),
    _locals,
    &CIM_Card::static_meta_class,
    2, /* num_keys */
    &__meta_repository_CCA3FB4C49C51F2D868FF3E04426D671,
};

CIMPLE_NAMESPACE_END

