/*NOCHKSRC*/
//==============================================================================
//
// PLEASE DO NOT EDIT; THIS FILE WAS AUTOMATICALLY GENERATED BY GENCLASS 2.0.24
//
//==============================================================================

#ifndef _cimple_SF_NICSAPImplementation_h
#define _cimple_SF_NICSAPImplementation_h

#include <cimple/cimple.h>
#include "CIM_DeviceSAPImplementation.h"

CIMPLE_NAMESPACE_BEGIN

// SF_NICSAPImplementation keys:

/*[1194]*/
class SF_NICSAPImplementation : public Instance
{
public:
    // CIM_Dependency features:
    CIM_LogicalDevice* Antecedent;
    CIM_ServiceAccessPoint* Dependent;

    // CIM_DeviceSAPImplementation features:

    // SF_NICSAPImplementation features:

    CIMPLE_CLASS(SF_NICSAPImplementation)
};

CIMPLE_NAMESPACE_END

#endif /* _cimple_SF_NICSAPImplementation_h */
