/*NOCHKSRC*/
//==============================================================================
//
// PLEASE DO NOT EDIT; THIS FILE WAS AUTOMATICALLY GENERATED BY GENCLASS 2.0.24
//
//==============================================================================

#include <cimple/Meta_Class.h>
#include <cimple/Meta_Property.h>
#include <cimple/Meta_Reference.h>
#include "SF_PhysicalConnector.h"

CIMPLE_NAMESPACE_BEGIN

using namespace cimple;

extern const Meta_Repository __meta_repository_25890684DE9F1ED99AF8E12287919123;

/*[1568]*/
extern const Meta_Property
_CIM_ManagedElement_InstanceID;

/*[1568]*/
extern const Meta_Property
_CIM_ManagedElement_Caption;

/*[1568]*/
extern const Meta_Property
_CIM_PhysicalElement_Description;

/*[1568]*/
extern const Meta_Property
_CIM_PhysicalElement_ElementName;

/*[1568]*/
extern const Meta_Property
_CIM_ManagedSystemElement_InstallDate;

/*[1568]*/
extern const Meta_Property
_CIM_ManagedSystemElement_Name;

/*[1568]*/
extern const Meta_Property
_CIM_ManagedSystemElement_OperationalStatus;

/*[1568]*/
extern const Meta_Property
_CIM_ManagedSystemElement_StatusDescriptions;

/*[1568]*/
extern const Meta_Property
_CIM_ManagedSystemElement_Status;

/*[1568]*/
extern const Meta_Property
_CIM_ManagedSystemElement_HealthState;

/*[1568]*/
extern const Meta_Property
_CIM_ManagedSystemElement_CommunicationStatus;

/*[1568]*/
extern const Meta_Property
_CIM_ManagedSystemElement_DetailedStatus;

/*[1568]*/
extern const Meta_Property
_CIM_ManagedSystemElement_OperatingStatus;

/*[1568]*/
extern const Meta_Property
_CIM_ManagedSystemElement_PrimaryStatus;

/*[1568]*/
extern const Meta_Property
_CIM_PhysicalElement_Tag;

/*[1568]*/
extern const Meta_Property
_CIM_PhysicalElement_CreationClassName;

/*[1568]*/
extern const Meta_Property
_CIM_PhysicalElement_Manufacturer;

/*[1568]*/
extern const Meta_Property
_CIM_PhysicalElement_Model;

/*[1568]*/
extern const Meta_Property
_CIM_PhysicalElement_SKU;

/*[1568]*/
extern const Meta_Property
_CIM_PhysicalElement_SerialNumber;

/*[1568]*/
extern const Meta_Property
_CIM_PhysicalElement_Version;

/*[1568]*/
extern const Meta_Property
_CIM_PhysicalElement_PartNumber;

/*[1568]*/
extern const Meta_Property
_CIM_PhysicalElement_OtherIdentifyingInfo;

/*[1568]*/
extern const Meta_Property
_CIM_PhysicalElement_PoweredOn;

/*[1568]*/
extern const Meta_Property
_CIM_PhysicalElement_ManufactureDate;

/*[1568]*/
extern const Meta_Property
_CIM_PhysicalElement_VendorEquipmentType;

/*[1568]*/
extern const Meta_Property
_CIM_PhysicalElement_UserTracking;

/*[1568]*/
extern const Meta_Property
_CIM_PhysicalElement_CanBeFRUed;

/*[1568]*/
extern const Meta_Property
_CIM_PhysicalConnector_ConnectorPinout;

/*[1568]*/
extern const Meta_Property
_CIM_PhysicalConnector_ConnectorType;

/*[1568]*/
extern const Meta_Property
_CIM_PhysicalConnector_OtherTypeDescription;

/*[1568]*/
extern const Meta_Property
_CIM_PhysicalConnector_ConnectorGender;

/*[1568]*/
extern const Meta_Property
_CIM_PhysicalConnector_ConnectorElectricalCharacteristics;

/*[1568]*/
extern const Meta_Property
_CIM_PhysicalConnector_OtherElectricalCharacteristics;

/*[1568]*/
extern const Meta_Property
_CIM_PhysicalConnector_NumPhysicalPins;

/*[1568]*/
extern const Meta_Property
_CIM_PhysicalConnector_ConnectorLayout;

/*[1568]*/
extern const Meta_Property
_CIM_PhysicalConnector_ConnectorDescription;

/*[2291]*/
static Meta_Feature* _SF_PhysicalConnector_MFA[] =
{
    (Meta_Feature*)(void*)&_CIM_ManagedElement_InstanceID,
    (Meta_Feature*)(void*)&_CIM_ManagedElement_Caption,
    (Meta_Feature*)(void*)&_CIM_PhysicalElement_Description,
    (Meta_Feature*)(void*)&_CIM_PhysicalElement_ElementName,
    (Meta_Feature*)(void*)&_CIM_ManagedSystemElement_InstallDate,
    (Meta_Feature*)(void*)&_CIM_ManagedSystemElement_Name,
    (Meta_Feature*)(void*)&_CIM_ManagedSystemElement_OperationalStatus,
    (Meta_Feature*)(void*)&_CIM_ManagedSystemElement_StatusDescriptions,
    (Meta_Feature*)(void*)&_CIM_ManagedSystemElement_Status,
    (Meta_Feature*)(void*)&_CIM_ManagedSystemElement_HealthState,
    (Meta_Feature*)(void*)&_CIM_ManagedSystemElement_CommunicationStatus,
    (Meta_Feature*)(void*)&_CIM_ManagedSystemElement_DetailedStatus,
    (Meta_Feature*)(void*)&_CIM_ManagedSystemElement_OperatingStatus,
    (Meta_Feature*)(void*)&_CIM_ManagedSystemElement_PrimaryStatus,
    (Meta_Feature*)(void*)&_CIM_PhysicalElement_Tag,
    (Meta_Feature*)(void*)&_CIM_PhysicalElement_CreationClassName,
    (Meta_Feature*)(void*)&_CIM_PhysicalElement_Manufacturer,
    (Meta_Feature*)(void*)&_CIM_PhysicalElement_Model,
    (Meta_Feature*)(void*)&_CIM_PhysicalElement_SKU,
    (Meta_Feature*)(void*)&_CIM_PhysicalElement_SerialNumber,
    (Meta_Feature*)(void*)&_CIM_PhysicalElement_Version,
    (Meta_Feature*)(void*)&_CIM_PhysicalElement_PartNumber,
    (Meta_Feature*)(void*)&_CIM_PhysicalElement_OtherIdentifyingInfo,
    (Meta_Feature*)(void*)&_CIM_PhysicalElement_PoweredOn,
    (Meta_Feature*)(void*)&_CIM_PhysicalElement_ManufactureDate,
    (Meta_Feature*)(void*)&_CIM_PhysicalElement_VendorEquipmentType,
    (Meta_Feature*)(void*)&_CIM_PhysicalElement_UserTracking,
    (Meta_Feature*)(void*)&_CIM_PhysicalElement_CanBeFRUed,
    (Meta_Feature*)(void*)&_CIM_PhysicalConnector_ConnectorPinout,
    (Meta_Feature*)(void*)&_CIM_PhysicalConnector_ConnectorType,
    (Meta_Feature*)(void*)&_CIM_PhysicalConnector_OtherTypeDescription,
    (Meta_Feature*)(void*)&_CIM_PhysicalConnector_ConnectorGender,
    (Meta_Feature*)(void*)&_CIM_PhysicalConnector_ConnectorElectricalCharacteristics,
    (Meta_Feature*)(void*)&_CIM_PhysicalConnector_OtherElectricalCharacteristics,
    (Meta_Feature*)(void*)&_CIM_PhysicalConnector_NumPhysicalPins,
    (Meta_Feature*)(void*)&_CIM_PhysicalConnector_ConnectorLayout,
    (Meta_Feature*)(void*)&_CIM_PhysicalConnector_ConnectorDescription,
};

/*[2338]*/
static const Meta_Feature_Local _locals[] =
{
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
};

/*[2358]*/
const Meta_Class SF_PhysicalConnector::static_meta_class =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_CLASS,
    "SF_PhysicalConnector",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _SF_PhysicalConnector_MFA,
    CIMPLE_ARRAY_SIZE(_SF_PhysicalConnector_MFA),
    sizeof(SF_PhysicalConnector),
    _locals,
    &CIM_PhysicalConnector::static_meta_class,
    2, /* num_keys */
    &__meta_repository_25890684DE9F1ED99AF8E12287919123,
};

CIMPLE_NAMESPACE_END

