// Generated by genprov 2.0.24
#ifndef _SF_RegisteredProfile_Provider_h
#define _SF_RegisteredProfile_Provider_h

#include <cimple/cimple.h>
#include "SF_RegisteredProfile.h"
#include "sf_provider.h"

CIMPLE_NAMESPACE_BEGIN

class SF_RegisteredProfile_Provider
{
public:

    typedef SF_RegisteredProfile Class;

    SF_RegisteredProfile_Provider();

    ~SF_RegisteredProfile_Provider();

    Load_Status load();

    Unload_Status unload();

    Get_Instance_Status get_instance(
        const SF_RegisteredProfile* model,
        SF_RegisteredProfile*& instance);

    Enum_Instances_Status enum_instances(
        const SF_RegisteredProfile* model,
        Enum_Instances_Handler<SF_RegisteredProfile>* handler);

    Create_Instance_Status create_instance(
        SF_RegisteredProfile* instance);

    Delete_Instance_Status delete_instance(
        const SF_RegisteredProfile* instance);

    Modify_Instance_Status modify_instance(
        const SF_RegisteredProfile* model,
        const SF_RegisteredProfile* instance);

    Invoke_Method_Status CloseConformantInstances(
        const SF_RegisteredProfile* self,
        const Property<String>& EnumerationContext,
        Property<uint32>& return_value);

    Invoke_Method_Status OpenConformantInstances(
        const SF_RegisteredProfile* self,
        const Property<String>& ResultClass,
        const Property<Array_String>& IncludedPropertyList,
        const Property<uint32>& OperationTimeout,
        const Property<boolean>& ContinueOnError,
        const Property<uint32>& MaxObjectCount,
        Property<String>& EnumerationContext,
        Property<boolean>& EndOfSequence,
        Property<Array_uint16>& InstanceType,
        Property< Array<CIM_ManagedElement*> >& InstanceWithPathList,
        Property<uint32>& return_value);

    Invoke_Method_Status PullConformantInstances(
        const SF_RegisteredProfile* self,
        const Property<uint32>& MaxObjectCount,
        Property<String>& EnumerationContext,
        Property<boolean>& EndOfSequence,
        Property<Array_uint16>& InstanceType,
        Property< Array<CIM_ManagedElement*> >& InstanceWithPathList,
        Property<uint32>& return_value);

    /*@END@*/
};

CIMPLE_NAMESPACE_END

#endif /* _SF_RegisteredProfile_Provider_h */
