/*NOCHKSRC*/
//==============================================================================
//
// PLEASE DO NOT EDIT; THIS FILE WAS AUTOMATICALLY GENERATED BY GENCLASS 2.0.24
//
//==============================================================================

#ifndef _cimple_SF_RecordAppliesToElement_h
#define _cimple_SF_RecordAppliesToElement_h

#include <cimple/cimple.h>
#include "CIM_RecordAppliesToElement.h"

CIMPLE_NAMESPACE_BEGIN

// SF_RecordAppliesToElement keys:

/*[1194]*/
class SF_RecordAppliesToElement : public Instance
{
public:
    // CIM_Dependency features:
    CIM_RecordForLog* Antecedent;
    CIM_ManagedElement* Dependent;

    // CIM_RecordAppliesToElement features:

    // SF_RecordAppliesToElement features:

    CIMPLE_CLASS(SF_RecordAppliesToElement)
};

CIMPLE_NAMESPACE_END

#endif /* _cimple_SF_RecordAppliesToElement_h */
