/*NOCHKSRC*/
//==============================================================================
//
// PLEASE DO NOT EDIT; THIS FILE WAS AUTOMATICALLY GENERATED BY GENCLASS 2.0.24
//
//==============================================================================

#include <cimple/Meta_Class.h>
#include <cimple/Meta_Property.h>
#include <cimple/Meta_Reference.h>
#include "SF_SystemDevice.h"

CIMPLE_NAMESPACE_BEGIN

using namespace cimple;

extern const Meta_Repository __meta_repository_322BD996DC5A15A5B9D5D42DDD2F5A5E;

/*[1653]*/
extern const Meta_Reference
_CIM_SystemDevice_GroupComponent;

/*[1653]*/
extern const Meta_Reference
_CIM_SystemDevice_PartComponent;

/*[2291]*/
static Meta_Feature* _SF_SystemDevice_MFA[] =
{
    (Meta_Feature*)(void*)&_CIM_SystemDevice_GroupComponent,
    (Meta_Feature*)(void*)&_CIM_SystemDevice_PartComponent,
};

/*[2338]*/
static const Meta_Feature_Local _locals[] =
{
    {0},
    {0},
};

/*[2358]*/
const Meta_Class SF_SystemDevice::static_meta_class =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_ASSOCIATION|CIMPLE_FLAG_AGGREGATION,
    "SF_SystemDevice",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _SF_SystemDevice_MFA,
    CIMPLE_ARRAY_SIZE(_SF_SystemDevice_MFA),
    sizeof(SF_SystemDevice),
    _locals,
    &CIM_SystemDevice::static_meta_class,
    2, /* num_keys */
    &__meta_repository_322BD996DC5A15A5B9D5D42DDD2F5A5E,
};

CIMPLE_NAMESPACE_END

