/*NOCHKSRC*/
//==============================================================================
//
// PLEASE DO NOT EDIT; THIS FILE WAS AUTOMATICALLY GENERATED BY GENCLASS 2.0.24
//
//==============================================================================

#include <cimple/Meta_Class.h>
#include <cimple/Meta_Property.h>
#include <cimple/Meta_Reference.h>
#include "SF_SoftwareIdentity.h"

CIMPLE_NAMESPACE_BEGIN

using namespace cimple;

extern const Meta_Repository __meta_repository_322BD996DC5A15A5B9D5D42DDD2F5A5E;

/*[1568]*/
extern const Meta_Property
_CIM_SoftwareIdentity_InstanceID;

/*[1568]*/
extern const Meta_Property
_CIM_ManagedElement_Caption;

/*[1568]*/
extern const Meta_Property
_CIM_ManagedElement_Description;

/*[1568]*/
extern const Meta_Property
_CIM_ManagedElement_ElementName;

/*[1568]*/
extern const Meta_Property
_CIM_ManagedSystemElement_InstallDate;

/*[1568]*/
extern const Meta_Property
_CIM_ManagedSystemElement_Name;

/*[1568]*/
extern const Meta_Property
_CIM_ManagedSystemElement_OperationalStatus;

/*[1568]*/
extern const Meta_Property
_CIM_ManagedSystemElement_StatusDescriptions;

/*[1568]*/
extern const Meta_Property
_CIM_ManagedSystemElement_Status;

/*[1568]*/
extern const Meta_Property
_CIM_ManagedSystemElement_HealthState;

/*[1568]*/
extern const Meta_Property
_CIM_ManagedSystemElement_CommunicationStatus;

/*[1568]*/
extern const Meta_Property
_CIM_ManagedSystemElement_DetailedStatus;

/*[1568]*/
extern const Meta_Property
_CIM_ManagedSystemElement_OperatingStatus;

/*[1568]*/
extern const Meta_Property
_CIM_ManagedSystemElement_PrimaryStatus;

/*[1568]*/
extern const Meta_Property
_CIM_SoftwareIdentity_MajorVersion;

/*[1568]*/
extern const Meta_Property
_CIM_SoftwareIdentity_MinorVersion;

/*[1568]*/
extern const Meta_Property
_CIM_SoftwareIdentity_RevisionNumber;

/*[1568]*/
extern const Meta_Property
_CIM_SoftwareIdentity_BuildNumber;

/*[1568]*/
extern const Meta_Property
_CIM_SoftwareIdentity_LargeBuildNumber;

/*[1568]*/
extern const Meta_Property
_CIM_SoftwareIdentity_IsLargeBuildNumber;

/*[1568]*/
extern const Meta_Property
_CIM_SoftwareIdentity_VersionString;

/*[1568]*/
extern const Meta_Property
_CIM_SoftwareIdentity_TargetOperatingSystems;

/*[1568]*/
extern const Meta_Property
_CIM_SoftwareIdentity_Manufacturer;

/*[1568]*/
extern const Meta_Property
_CIM_SoftwareIdentity_Languages;

/*[1568]*/
extern const Meta_Property
_CIM_SoftwareIdentity_Classifications;

/*[1568]*/
extern const Meta_Property
_CIM_SoftwareIdentity_ClassificationDescriptions;

/*[1568]*/
extern const Meta_Property
_CIM_SoftwareIdentity_SerialNumber;

/*[1568]*/
extern const Meta_Property
_CIM_SoftwareIdentity_TargetTypes;

/*[1568]*/
extern const Meta_Property
_CIM_SoftwareIdentity_IdentityInfoValue;

/*[1568]*/
extern const Meta_Property
_CIM_SoftwareIdentity_IdentityInfoType;

/*[1568]*/
extern const Meta_Property
_CIM_SoftwareIdentity_ReleaseDate;

/*[1568]*/
extern const Meta_Property
_CIM_SoftwareIdentity_IsEntity;

/*[1568]*/
extern const Meta_Property
_CIM_SoftwareIdentity_ExtendedResourceType;

/*[1568]*/
extern const Meta_Property
_CIM_SoftwareIdentity_OtherExtendedResourceTypeDescription;

/*[1568]*/
extern const Meta_Property
_CIM_SoftwareIdentity_MinExtendedResourceTypeMajorVersion;

/*[1568]*/
extern const Meta_Property
_CIM_SoftwareIdentity_MinExtendedResourceTypeMinorVersion;

/*[1568]*/
extern const Meta_Property
_CIM_SoftwareIdentity_MinExtendedResourceTypeRevisionNumber;

/*[1568]*/
extern const Meta_Property
_CIM_SoftwareIdentity_MinExtendedResourceTypeBuildNumber;

/*[1568]*/
extern const Meta_Property
_CIM_SoftwareIdentity_TargetOSTypes;

/*[2291]*/
static Meta_Feature* _SF_SoftwareIdentity_MFA[] =
{
    (Meta_Feature*)(void*)&_CIM_SoftwareIdentity_InstanceID,
    (Meta_Feature*)(void*)&_CIM_ManagedElement_Caption,
    (Meta_Feature*)(void*)&_CIM_ManagedElement_Description,
    (Meta_Feature*)(void*)&_CIM_ManagedElement_ElementName,
    (Meta_Feature*)(void*)&_CIM_ManagedSystemElement_InstallDate,
    (Meta_Feature*)(void*)&_CIM_ManagedSystemElement_Name,
    (Meta_Feature*)(void*)&_CIM_ManagedSystemElement_OperationalStatus,
    (Meta_Feature*)(void*)&_CIM_ManagedSystemElement_StatusDescriptions,
    (Meta_Feature*)(void*)&_CIM_ManagedSystemElement_Status,
    (Meta_Feature*)(void*)&_CIM_ManagedSystemElement_HealthState,
    (Meta_Feature*)(void*)&_CIM_ManagedSystemElement_CommunicationStatus,
    (Meta_Feature*)(void*)&_CIM_ManagedSystemElement_DetailedStatus,
    (Meta_Feature*)(void*)&_CIM_ManagedSystemElement_OperatingStatus,
    (Meta_Feature*)(void*)&_CIM_ManagedSystemElement_PrimaryStatus,
    (Meta_Feature*)(void*)&_CIM_SoftwareIdentity_MajorVersion,
    (Meta_Feature*)(void*)&_CIM_SoftwareIdentity_MinorVersion,
    (Meta_Feature*)(void*)&_CIM_SoftwareIdentity_RevisionNumber,
    (Meta_Feature*)(void*)&_CIM_SoftwareIdentity_BuildNumber,
    (Meta_Feature*)(void*)&_CIM_SoftwareIdentity_LargeBuildNumber,
    (Meta_Feature*)(void*)&_CIM_SoftwareIdentity_IsLargeBuildNumber,
    (Meta_Feature*)(void*)&_CIM_SoftwareIdentity_VersionString,
    (Meta_Feature*)(void*)&_CIM_SoftwareIdentity_TargetOperatingSystems,
    (Meta_Feature*)(void*)&_CIM_SoftwareIdentity_Manufacturer,
    (Meta_Feature*)(void*)&_CIM_SoftwareIdentity_Languages,
    (Meta_Feature*)(void*)&_CIM_SoftwareIdentity_Classifications,
    (Meta_Feature*)(void*)&_CIM_SoftwareIdentity_ClassificationDescriptions,
    (Meta_Feature*)(void*)&_CIM_SoftwareIdentity_SerialNumber,
    (Meta_Feature*)(void*)&_CIM_SoftwareIdentity_TargetTypes,
    (Meta_Feature*)(void*)&_CIM_SoftwareIdentity_IdentityInfoValue,
    (Meta_Feature*)(void*)&_CIM_SoftwareIdentity_IdentityInfoType,
    (Meta_Feature*)(void*)&_CIM_SoftwareIdentity_ReleaseDate,
    (Meta_Feature*)(void*)&_CIM_SoftwareIdentity_IsEntity,
    (Meta_Feature*)(void*)&_CIM_SoftwareIdentity_ExtendedResourceType,
    (Meta_Feature*)(void*)&_CIM_SoftwareIdentity_OtherExtendedResourceTypeDescription,
    (Meta_Feature*)(void*)&_CIM_SoftwareIdentity_MinExtendedResourceTypeMajorVersion,
    (Meta_Feature*)(void*)&_CIM_SoftwareIdentity_MinExtendedResourceTypeMinorVersion,
    (Meta_Feature*)(void*)&_CIM_SoftwareIdentity_MinExtendedResourceTypeRevisionNumber,
    (Meta_Feature*)(void*)&_CIM_SoftwareIdentity_MinExtendedResourceTypeBuildNumber,
    (Meta_Feature*)(void*)&_CIM_SoftwareIdentity_TargetOSTypes,
};

/*[2338]*/
static const Meta_Feature_Local _locals[] =
{
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
};

/*[2358]*/
const Meta_Class SF_SoftwareIdentity::static_meta_class =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_CLASS,
    "SF_SoftwareIdentity",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _SF_SoftwareIdentity_MFA,
    CIMPLE_ARRAY_SIZE(_SF_SoftwareIdentity_MFA),
    sizeof(SF_SoftwareIdentity),
    _locals,
    &CIM_SoftwareIdentity::static_meta_class,
    1, /* num_keys */
    &__meta_repository_322BD996DC5A15A5B9D5D42DDD2F5A5E,
};

CIMPLE_NAMESPACE_END

