/*NOCHKSRC*/
//==============================================================================
//
// PLEASE DO NOT EDIT; THIS FILE WAS AUTOMATICALLY GENERATED BY GENCLASS 2.0.24
//
//==============================================================================

#ifndef _cimple_SF_UseOfLog_h
#define _cimple_SF_UseOfLog_h

#include <cimple/cimple.h>
#include "CIM_UseOfLog.h"

CIMPLE_NAMESPACE_BEGIN

// SF_UseOfLog keys:

/*[1194]*/
class SF_UseOfLog : public Instance
{
public:
    // CIM_Dependency features:
    CIM_Log* Antecedent;
    CIM_ManagedSystemElement* Dependent;

    // CIM_UseOfLog features:
    Property<String> RecordedData;

    // SF_UseOfLog features:

    CIMPLE_CLASS(SF_UseOfLog)
};

CIMPLE_NAMESPACE_END

#endif /* _cimple_SF_UseOfLog_h */
