libprovider_SOURCES = CIM_AffectedJobElement.cpp \
	CIM_AvailableDiagnosticService.cpp \
	CIM_Capabilities.cpp \
	CIM_Card.cpp \
	CIM_Collection.cpp \
	CIM_CollectionOfMSEs.cpp \
	CIM_Component.cpp \
	CIM_ComputerSystem.cpp \
	CIM_ConcreteJob.cpp \
	CIM_ConnectorOnPackage.cpp \
	CIM_Container.cpp \
	CIM_ControlledBy.cpp \
	CIM_Controller.cpp \
	CIM_Dependency.cpp \
	CIM_DeviceConnection.cpp \
	CIM_DeviceSAPImplementation.cpp \
	CIM_DiagnosticCompletionRecord.cpp \
	CIM_DiagnosticLog.cpp \
	CIM_DiagnosticRecord.cpp \
	CIM_DiagnosticResult.cpp \
	CIM_DiagnosticService.cpp \
	CIM_DiagnosticServiceCapabilities.cpp \
	CIM_DiagnosticServiceRecord.cpp \
	CIM_DiagnosticSetting.cpp \
	CIM_DiagnosticSettingData.cpp \
	CIM_DiagnosticTest.cpp \
	CIM_ElementCapabilities.cpp \
	CIM_ElementConformsToProfile.cpp \
	CIM_ElementSettingData.cpp \
	CIM_ElementSoftwareIdentity.cpp \
	CIM_EnabledLogicalElement.cpp \
	CIM_EnabledLogicalElementCapabilities.cpp \
	CIM_Error.cpp \
	CIM_EthernetPort.cpp \
	CIM_HostedAccessPoint.cpp \
	CIM_HostedDependency.cpp \
	CIM_HostedService.cpp \
	CIM_InstalledSoftwareIdentity.cpp \
	CIM_Job.cpp \
	CIM_JobSettingData.cpp \
	CIM_LANEndpoint.cpp \
	CIM_Log.cpp \
	CIM_LogEntry.cpp \
	CIM_LogManagesRecord.cpp \
	CIM_LogicalDevice.cpp \
	CIM_LogicalElement.cpp \
	CIM_LogicalPort.cpp \
	CIM_ManagedElement.cpp \
	CIM_ManagedSystemElement.cpp \
	CIM_NetworkPort.cpp \
	CIM_OperatingSystem.cpp \
	CIM_OrderedComponent.cpp \
	CIM_OwningJobElement.cpp \
	CIM_PhysicalConnector.cpp \
	CIM_PhysicalElement.cpp \
	CIM_PhysicalPackage.cpp \
	CIM_PortController.cpp \
	CIM_ProtocolEndpoint.cpp \
	CIM_Realizes.cpp \
	CIM_RecordAppliesToElement.cpp \
	CIM_RecordForLog.cpp \
	CIM_RecordLog.cpp \
	CIM_ReferencedProfile.cpp \
	CIM_RegisteredProfile.cpp \
	CIM_Service.cpp \
	CIM_ServiceAccessPoint.cpp \
	CIM_ServiceAffectsElement.cpp \
	CIM_ServiceAvailableToElement.cpp \
	CIM_Setting.cpp \
	CIM_SettingData.cpp \
	CIM_SoftwareIdentity.cpp \
	CIM_SoftwareInstallationService.cpp \
	CIM_SoftwareInstallationServiceCapabilities.cpp \
	CIM_System.cpp \
	CIM_SystemComponent.cpp \
	CIM_SystemDevice.cpp \
	CIM_UseOfLog.cpp \
	CIM_ReferencedSpecification.cpp \
	CIM_RegisteredSpecification.cpp \
	SF_AffectedJobElement.cpp \
	SF_AffectedJobElement_Provider.cpp \
	SF_AvailableDiagnosticService.cpp \
	SF_AvailableDiagnosticService_Provider.cpp \
	SF_BundleComponent.cpp \
	SF_BundleComponent_Provider.cpp \
	SF_ComputerSystem.cpp \
	SF_ComputerSystem_Provider.cpp \
	SF_ConcreteJob.cpp \
	SF_ConcreteJob_Provider.cpp \
	SF_ConnectorOnNIC.cpp \
	SF_ConnectorOnNIC_Provider.cpp \
	SF_ConnectorRealizesPort.cpp \
	SF_ConnectorRealizesPort_Provider.cpp \
	SF_ControlledBy.cpp \
	SF_ControlledBy_Provider.cpp \
	SF_DiagnosticCompletionRecord.cpp \
	SF_DiagnosticCompletionRecord_Provider.cpp \
	SF_DiagnosticLog.cpp \
	SF_DiagnosticLog_Provider.cpp \
	SF_DiagnosticServiceCapabilities.cpp \
	SF_DiagnosticServiceCapabilities_Provider.cpp \
	SF_DiagnosticSettingData.cpp \
	SF_DiagnosticSettingData_Provider.cpp \
	SF_DiagnosticTest.cpp \
	SF_DiagnosticTest_Provider.cpp \
	SF_ElementCapabilities.cpp \
	SF_ElementCapabilities_Provider.cpp \
	SF_ElementConformsToProfile.cpp \
	SF_ElementConformsToProfile_Provider.cpp \
	SF_ElementSettingData.cpp \
	SF_ElementSettingData_Provider.cpp \
	SF_ElementSoftwareIdentity.cpp \
	SF_ElementSoftwareIdentity_Provider.cpp \
	SF_EnabledLogicalElementCapabilities.cpp \
	SF_EnabledLogicalElementCapabilities_Provider.cpp \
	SF_EthernetPort.cpp \
	SF_EthernetPort_Provider.cpp \
	SF_HostedAccessPoint.cpp \
	SF_HostedAccessPoint_Provider.cpp \
	SF_HostedService.cpp \
	SF_HostedService_Provider.cpp \
	SF_InstalledSoftwareIdentity.cpp \
	SF_InstalledSoftwareIdentity_Provider.cpp \
	SF_LANEndpoint.cpp \
	SF_LANEndpoint_Provider.cpp \
	SF_LogEntry.cpp \
	SF_LogEntry_Provider.cpp \
	SF_LogManagesRecord.cpp \
	SF_LogManagesRecord_Provider.cpp \
	SF_NICCard.cpp \
	SF_NICCard_Provider.cpp \
	SF_NICSAPImplementation.cpp \
	SF_NICSAPImplementation_Provider.cpp \
	SF_OwningJobElement.cpp \
	SF_OwningJobElement_Provider.cpp \
	SF_PhysicalConnector.cpp \
	SF_PhysicalConnector_Provider.cpp \
	SF_PortController.cpp \
	SF_PortController_Provider.cpp \
	SF_RecordAppliesToElement.cpp \
	SF_RecordAppliesToElement_Provider.cpp \
	SF_RecordLog.cpp \
	SF_RecordLog_Provider.cpp \
	SF_ReferencedProfile.cpp \
	SF_ReferencedProfile_Provider.cpp \
	SF_RegisteredProfile.cpp \
	SF_RegisteredProfile_Provider.cpp \
	SF_ServiceAffectsElement.cpp \
	SF_ServiceAffectsElement_Provider.cpp \
	SF_SoftwareIdentity.cpp \
	SF_SoftwareIdentity_Provider.cpp \
	SF_SoftwareInstallationService.cpp \
	SF_SoftwareInstallationServiceCapabilities.cpp \
	SF_SoftwareInstallationServiceCapabilities_Provider.cpp \
	SF_SoftwareInstallationService_Provider.cpp \
	SF_SystemDevice.cpp \
	SF_SystemDevice_Provider.cpp \
	SF_UseOfLog.cpp \
	SF_UseOfLog_Provider.cpp \
	module.cpp \
	repository.cpp \
	sf_core.cpp \
	sf_logging.cpp \
	sf_platform.cpp \
	sf_sample.cpp \
	sf_threads.cpp \
	sf_utils.cpp \
	sf_helpers.cpp \
	sf_nic_helpers.cpp \
	sf_port_helpers.cpp \
	sf_intf_helpers.cpp \
	sf_diag_helpers.cpp \
	sf_sw_helpers.cpp \
	sf_sys_helpers.cpp

libprovider_DIR = .
libprovider_TARGET = lib$(PROVIDER_LIBRARY).so

$(eval $(call component,libprovider,SHARED_LIBRARIES))

$(libprovider_TARGET) : $(CIMPLE_LIBS)
