PROVIDER_LIBRARY=Solarflare
PROVIDER_VERSION_MAJOR=1
PROVIDER_VERSION_MINOR=0
PROVIDER_VERSION=$(PROVIDER_VERSION_MAJOR).$(PROVIDER_VERSION_MINOR)
PROVIDER_REVISION=1.0
PROVIDER_DESCRIPTION = Solarflare NIC CIM Provider
PROVIDER_VENDOR = Solarflare Communications
