/* This file is autogenerated, do not manually alter.    */
/* If you are in the v5 tree, you can refresh headers    */
/* with the genheader utility in .../v5/scripts          */
#ifndef	MCPUMCGMAC_PROGMODEL_DEFS_H
#define	MCPUMCGMAC_PROGMODEL_DEFS_H

/*------------------------------------------------------------*/
/*
 * FMCR_CZ_MC_GM_CFG1_REG(32bit):
 * GMAC configuration register 1
 */
#define	FMCR_CZ_MC_GM_CFG1_REG 0x00a00000
/* sienaa0,hunta0=mcpu_addr_map */

#define	FMCRF_CZ_GM_SW_RST_LBN 31
#define	FMCRF_CZ_GM_SW_RST_WIDTH 1
#define	FMCRF_CZ_GM_SIM_RST_LBN 30
#define	FMCRF_CZ_GM_SIM_RST_WIDTH 1
#define	FMCRF_CZ_GM_RST_RX_MAC_CTL_LBN 19
#define	FMCRF_CZ_GM_RST_RX_MAC_CTL_WIDTH 1
#define	FMCRF_CZ_GM_RST_TX_MAC_CTL_LBN 18
#define	FMCRF_CZ_GM_RST_TX_MAC_CTL_WIDTH 1
#define	FMCRF_CZ_GM_RST_RX_FUNC_LBN 17
#define	FMCRF_CZ_GM_RST_RX_FUNC_WIDTH 1
#define	FMCRF_CZ_GM_RST_TX_FUNC_LBN 16
#define	FMCRF_CZ_GM_RST_TX_FUNC_WIDTH 1
#define	FMCRF_CZ_GM_LOOP_LBN 8
#define	FMCRF_CZ_GM_LOOP_WIDTH 1
#define	FMCRF_CZ_GM_RX_FC_EN_LBN 5
#define	FMCRF_CZ_GM_RX_FC_EN_WIDTH 1
#define	FMCRF_CZ_GM_TX_FC_EN_LBN 4
#define	FMCRF_CZ_GM_TX_FC_EN_WIDTH 1
#define	FMCRF_CZ_GM_SYNC_RXEN_LBN 3
#define	FMCRF_CZ_GM_SYNC_RXEN_WIDTH 1
#define	FMCRF_CZ_GM_RX_EN_LBN 2
#define	FMCRF_CZ_GM_RX_EN_WIDTH 1
#define	FMCRF_CZ_GM_SYNC_TXEN_LBN 1
#define	FMCRF_CZ_GM_SYNC_TXEN_WIDTH 1
#define	FMCRF_CZ_GM_TX_EN_LBN 0
#define	FMCRF_CZ_GM_TX_EN_WIDTH 1


/*------------------------------------------------------------*/
/*
 * FMCR_CZ_MC_GM_CFG2_REG(32bit):
 * GMAC configuration register 2
 */
#define	FMCR_CZ_MC_GM_CFG2_REG 0x00a00004
/* sienaa0,hunta0=mcpu_addr_map */

#define	FMCRF_CZ_GM_PAMBL_LEN_LBN 12
#define	FMCRF_CZ_GM_PAMBL_LEN_WIDTH 4
#define	FMCRF_CZ_GM_IF_MODE_LBN 8
#define	FMCRF_CZ_GM_IF_MODE_WIDTH 2
#define	FMCFE_CZ_IF_MODE_BYTE_MODE 2
#define	FMCFE_CZ_IF_MODE_NIBBLE_MODE 1
#define	FMCFE_DZ_OTHER other
#define	FMCRF_CZ_GM_HUGE_FRM_EN_LBN 5
#define	FMCRF_CZ_GM_HUGE_FRM_EN_WIDTH 1
#define	FMCRF_CZ_GM_LEN_CHK_LBN 4
#define	FMCRF_CZ_GM_LEN_CHK_WIDTH 1
#define	FMCRF_CZ_GM_PAD_CRC_EN_LBN 2
#define	FMCRF_CZ_GM_PAD_CRC_EN_WIDTH 1
#define	FMCRF_CZ_GM_CRC_EN_LBN 1
#define	FMCRF_CZ_GM_CRC_EN_WIDTH 1
#define	FMCRF_CZ_GM_FD_LBN 0
#define	FMCRF_CZ_GM_FD_WIDTH 1


/*------------------------------------------------------------*/
/*
 * FMCR_CZ_MC_GM_IPG_REG(32bit):
 * GMAC IPG register
 */
#define	FMCR_CZ_MC_GM_IPG_REG 0x00a00008
/* sienaa0,hunta0=mcpu_addr_map */

#define	FMCRF_CZ_GM_NONB2B_IPG1_LBN 24
#define	FMCRF_CZ_GM_NONB2B_IPG1_WIDTH 7
#define	FMCRF_CZ_GM_NONB2B_IPG2_LBN 16
#define	FMCRF_CZ_GM_NONB2B_IPG2_WIDTH 7
#define	FMCRF_CZ_GM_MIN_IPG_ENF_LBN 8
#define	FMCRF_CZ_GM_MIN_IPG_ENF_WIDTH 8
#define	FMCRF_CZ_GM_B2B_IPG_LBN 0
#define	FMCRF_CZ_GM_B2B_IPG_WIDTH 7


/*------------------------------------------------------------*/
/*
 * FMCR_CZ_MC_GM_HD_REG(32bit):
 * GMAC half duplex register
 */
#define	FMCR_CZ_MC_GM_HD_REG 0x00a0000c
/* sienaa0,hunta0=mcpu_addr_map */

#define	FMCRF_CZ_GM_ALT_BOFF_VAL_LBN 20
#define	FMCRF_CZ_GM_ALT_BOFF_VAL_WIDTH 4
#define	FMCRF_CZ_GM_ALT_BOFF_EN_LBN 19
#define	FMCRF_CZ_GM_ALT_BOFF_EN_WIDTH 1
#define	FMCRF_CZ_GM_BP_NO_BOFF_LBN 18
#define	FMCRF_CZ_GM_BP_NO_BOFF_WIDTH 1
#define	FMCRF_CZ_GM_DIS_BOFF_LBN 17
#define	FMCRF_CZ_GM_DIS_BOFF_WIDTH 1
#define	FMCRF_CZ_GM_EXDEF_TX_EN_LBN 16
#define	FMCRF_CZ_GM_EXDEF_TX_EN_WIDTH 1
#define	FMCRF_CZ_GM_RTRY_LIMIT_LBN 12
#define	FMCRF_CZ_GM_RTRY_LIMIT_WIDTH 4
#define	FMCRF_CZ_GM_COL_WIN_LBN 0
#define	FMCRF_CZ_GM_COL_WIN_WIDTH 10


/*------------------------------------------------------------*/
/*
 * FMCR_CZ_MC_GM_MAX_FLEN_REG(32bit):
 * GMAC maximum frame length register
 */
#define	FMCR_CZ_MC_GM_MAX_FLEN_REG 0x00a00010
/* sienaa0,hunta0=mcpu_addr_map */

#define	FMCRF_CZ_GM_MAX_FLEN_LBN 0
#define	FMCRF_CZ_GM_MAX_FLEN_WIDTH 16


/*------------------------------------------------------------*/
/*
 * FMCR_CZ_MC_GM_TEST_REG(32bit):
 * GMAC test register
 */
#define	FMCR_CZ_MC_GM_TEST_REG 0x00a0001c
/* sienaa0,hunta0=mcpu_addr_map */

#define	FMCRF_CZ_GM_MAX_BOFF_LBN 3
#define	FMCRF_CZ_GM_MAX_BOFF_WIDTH 1
#define	FMCRF_CZ_GM_REG_TX_FLOW_EN_LBN 2
#define	FMCRF_CZ_GM_REG_TX_FLOW_EN_WIDTH 1
#define	FMCRF_CZ_GM_TEST_PAUSE_LBN 1
#define	FMCRF_CZ_GM_TEST_PAUSE_WIDTH 1
#define	FMCRF_CZ_GM_SHORT_SLOT_LBN 0
#define	FMCRF_CZ_GM_SHORT_SLOT_WIDTH 1


/*------------------------------------------------------------*/
/*
 * FMCR_CZ_MC_GM_ADR1_REG(32bit):
 * GMAC station address register 1
 */
#define	FMCR_CZ_MC_GM_ADR1_REG 0x00a00040
/* sienaa0,hunta0=mcpu_addr_map */

#define	FMCRF_CZ_GM_ADR_B0_LBN 24
#define	FMCRF_CZ_GM_ADR_B0_WIDTH 8
#define	FMCRF_CZ_GM_ADR_B1_LBN 16
#define	FMCRF_CZ_GM_ADR_B1_WIDTH 8
#define	FMCRF_CZ_GM_ADR_B2_LBN 8
#define	FMCRF_CZ_GM_ADR_B2_WIDTH 8
#define	FMCRF_CZ_GM_ADR_B3_LBN 0
#define	FMCRF_CZ_GM_ADR_B3_WIDTH 8


/*------------------------------------------------------------*/
/*
 * FMCR_CZ_MC_GM_ADR2_REG(32bit):
 * GMAC station address register 2
 */
#define	FMCR_CZ_MC_GM_ADR2_REG 0x00a00044
/* sienaa0,hunta0=mcpu_addr_map */

#define	FMCRF_CZ_GM_ADR_B4_LBN 24
#define	FMCRF_CZ_GM_ADR_B4_WIDTH 8
#define	FMCRF_CZ_GM_ADR_B5_LBN 16
#define	FMCRF_CZ_GM_ADR_B5_WIDTH 8


/*------------------------------------------------------------*/
/*
 * FMCR_CZ_MC_GMF_CFG0_REG(32bit):
 * GMAC FIFO configuration register 0
 */
#define	FMCR_CZ_MC_GMF_CFG0_REG 0x00a00048
/* sienaa0,hunta0=mcpu_addr_map */

#define	FMCRF_CZ_GMF_FTFENRPLY_LBN 20
#define	FMCRF_CZ_GMF_FTFENRPLY_WIDTH 1
#define	FMCRF_CZ_GMF_STFENRPLY_LBN 19
#define	FMCRF_CZ_GMF_STFENRPLY_WIDTH 1
#define	FMCRF_CZ_GMF_FRFENRPLY_LBN 18
#define	FMCRF_CZ_GMF_FRFENRPLY_WIDTH 1
#define	FMCRF_CZ_GMF_SRFENRPLY_LBN 17
#define	FMCRF_CZ_GMF_SRFENRPLY_WIDTH 1
#define	FMCRF_CZ_GMF_WTMENRPLY_LBN 16
#define	FMCRF_CZ_GMF_WTMENRPLY_WIDTH 1
#define	FMCRF_CZ_GMF_FTFENREQ_LBN 12
#define	FMCRF_CZ_GMF_FTFENREQ_WIDTH 1
#define	FMCRF_CZ_GMF_STFENREQ_LBN 11
#define	FMCRF_CZ_GMF_STFENREQ_WIDTH 1
#define	FMCRF_CZ_GMF_FRFENREQ_LBN 10
#define	FMCRF_CZ_GMF_FRFENREQ_WIDTH 1
#define	FMCRF_CZ_GMF_SRFENREQ_LBN 9
#define	FMCRF_CZ_GMF_SRFENREQ_WIDTH 1
#define	FMCRF_CZ_GMF_WTMENREQ_LBN 8
#define	FMCRF_CZ_GMF_WTMENREQ_WIDTH 1
#define	FMCRF_CZ_GMF_HSTRSTFT_LBN 4
#define	FMCRF_CZ_GMF_HSTRSTFT_WIDTH 1
#define	FMCRF_CZ_GMF_HSTRSTST_LBN 3
#define	FMCRF_CZ_GMF_HSTRSTST_WIDTH 1
#define	FMCRF_CZ_GMF_HSTRSTFR_LBN 2
#define	FMCRF_CZ_GMF_HSTRSTFR_WIDTH 1
#define	FMCRF_CZ_GMF_HSTRSTSR_LBN 1
#define	FMCRF_CZ_GMF_HSTRSTSR_WIDTH 1
#define	FMCRF_CZ_GMF_HSTRSTWT_LBN 0
#define	FMCRF_CZ_GMF_HSTRSTWT_WIDTH 1


/*------------------------------------------------------------*/
/*
 * FMCR_CZ_MC_GMF_CFG1_REG(32bit):
 * GMAC FIFO configuration register 1
 */
#define	FMCR_CZ_MC_GMF_CFG1_REG 0x00a0004c
/* sienaa0,hunta0=mcpu_addr_map */

#define	FMCRF_CZ_GMF_CFGFRTH_LBN 16
#define	FMCRF_CZ_GMF_CFGFRTH_WIDTH 5
#define	FMCRF_CZ_GMF_CFGXOFFRTX_LBN 0
#define	FMCRF_CZ_GMF_CFGXOFFRTX_WIDTH 16


/*------------------------------------------------------------*/
/*
 * FMCR_CZ_MC_GMF_CFG2_REG(32bit):
 * GMAC FIFO configuration register 2
 */
#define	FMCR_CZ_MC_GMF_CFG2_REG 0x00a00050
/* sienaa0,hunta0=mcpu_addr_map */

#define	FMCRF_CZ_GMF_CFGHWM_LBN 16
#define	FMCRF_CZ_GMF_CFGHWM_WIDTH 6
#define	FMCRF_CZ_GMF_CFGLWM_LBN 0
#define	FMCRF_CZ_GMF_CFGLWM_WIDTH 6


/*------------------------------------------------------------*/
/*
 * FMCR_CZ_MC_GMF_CFG3_REG(32bit):
 * GMAC FIFO configuration register 3
 */
#define	FMCR_CZ_MC_GMF_CFG3_REG 0x00a00054
/* sienaa0,hunta0=mcpu_addr_map */

#define	FMCRF_CZ_GMF_CFGHWMFT_LBN 16
#define	FMCRF_CZ_GMF_CFGHWMFT_WIDTH 6
#define	FMCRF_CZ_GMF_CFGFTTH_LBN 0
#define	FMCRF_CZ_GMF_CFGFTTH_WIDTH 6


/*------------------------------------------------------------*/
/*
 * FMCR_CZ_MC_GMF_CFG4_REG(32bit):
 * GMAC FIFO configuration register 4
 */
#define	FMCR_CZ_MC_GMF_CFG4_REG 0x00a00058
/* sienaa0,hunta0=mcpu_addr_map */

#define	FMCRF_CZ_GMF_HSTFLTRFRM_LBN 0
#define	FMCRF_CZ_GMF_HSTFLTRFRM_WIDTH 18


/*------------------------------------------------------------*/
/*
 * FMCR_CZ_MC_GMF_CFG5_REG(32bit):
 * GMAC FIFO configuration register 5
 */
#define	FMCR_CZ_MC_GMF_CFG5_REG 0x00a0005c
/* sienaa0,hunta0=mcpu_addr_map */

#define	FMCRF_CZ_GMF_CFGHDPLX_LBN 22
#define	FMCRF_CZ_GMF_CFGHDPLX_WIDTH 1
#define	FMCRF_CZ_GMF_SRFULL_LBN 21
#define	FMCRF_CZ_GMF_SRFULL_WIDTH 1
#define	FMCRF_CZ_GMF_HSTSRFULLCLR_LBN 20
#define	FMCRF_CZ_GMF_HSTSRFULLCLR_WIDTH 1
#define	FMCRF_CZ_GMF_CFGBYTMODE_LBN 19
#define	FMCRF_CZ_GMF_CFGBYTMODE_WIDTH 1
#define	FMCRF_CZ_GMF_HSTDRPLT64_LBN 18
#define	FMCRF_CZ_GMF_HSTDRPLT64_WIDTH 1
#define	FMCRF_CZ_GMF_HSTFLTRFRMDC_LBN 0
#define	FMCRF_CZ_GMF_HSTFLTRFRMDC_WIDTH 18


#endif /* MCPUMCGMAC_PROGMODEL_DEFS_H */
