#pragma include ("qualifiers.mof")
#pragma include ("qualifiers_optional.mof")
#pragma include ("wmiqualifiers.mof")
#pragma include ("cimwin32.mof")
#pragma include ("CIM_Collection.mof")
#pragma include ("CIM_SoftwareIdentity.mof")
#pragma include ("CIM_ConcreteJob.mof")
#pragma include ("CIM_InstalledSoftwareIdentity.mof")
#pragma include ("CIM_ElementSoftwareIdentity.mof")
#pragma include ("CIM_OrderedComponent.mof")
#pragma include ("CIM_LogicalPort.mof")
#pragma include ("CIM_NetworkPort.mof")
#pragma include ("CIM_EthernetPort.mof")
#pragma include ("CIM_PortController.mof")
#pragma include ("CIM_ProtocolEndpoint.mof")
#pragma include ("CIM_LANEndpoint.mof")
#pragma include ("CIM_SoftwareInstallationService.mof")
#pragma include ("CIM_Capabilities.mof")
#pragma include ("CIM_EnabledLogicalElement.mof")
#pragma include ("CIM_EnabledLogicalElementCapabilities.mof")
#pragma include ("CIM_ElementCapabilities.mof")
#pragma include ("CIM_ServiceAffectsElement.mof")
#pragma include ("CIM_SoftwareInstallationServiceCapabilities.mof")
#pragma include ("CIM_Log.mof")
#pragma include ("CIM_RecordLog.mof")
#pragma include ("CIM_RecordLogCapabilities.mof")
#pragma include ("CIM_DiagnosticLog.mof")
#pragma include ("CIM_RecordForLog.mof")
#pragma include ("CIM_LogEntry.mof")
#pragma include ("CIM_SettingData.mof")
#pragma include ("CIM_JobSettingData.mof")
#pragma include ("CIM_DiagnosticResult.mof")
#pragma include ("CIM_DiagnosticSetting.mof")
#pragma include ("CIM_DiagnosticRecord.mof")
#pragma include ("CIM_DiagnosticServiceRecord.mof")
#pragma include ("CIM_DiagnosticCompletionRecord.mof")
#pragma include ("CIM_LogManagesRecord.mof")
#pragma include ("CIM_UseOfLog.mof")
#pragma include ("CIM_DiagnosticService.mof")
#pragma include ("CIM_DiagnosticServiceCapabilities.mof")
#pragma include ("CIM_DiagnosticTest.mof")
#pragma include ("CIM_RecordAppliesToElement.mof")
#pragma include ("CIM_OwningJobElement.mof")
#pragma include ("CIM_AffectedJobElement.mof")
#pragma include ("CIM_ServiceAvailableToElement.mof")
#pragma include ("CIM_AvailableDiagnosticService.mof")
#pragma include ("CIM_DiagnosticSettingData.mof")
#pragma include ("CIM_ElementSettingData.mof")
#pragma include ("CIM_RegisteredProfile.mof")
#pragma include ("CIM_ReferencedProfile.mof")
#pragma include ("CIM_ElementConformsToProfile.mof")
#pragma include ("CIM_InstIndication.mof")
#pragma include ("CIM_InstCreation.mof")
#pragma include ("CIM_InstModification.mof")
#pragma include ("CIM_ProcessIndication.mof")
#pragma include ("CIM_AlertIndication.mof")
#pragma include ("CIM_Error.mof")