#pragma include ("DMTF/Interop/CIM_CIMOMStatisticalData.mof")
#pragma include ("DMTF/Interop/CIM_Error.mof")
#pragma include ("DMTF/Interop/CIM_Namespace.mof")
#pragma include ("DMTF/Interop/CIM_RegisteredSpecification.mof")
#pragma include ("DMTF/Interop/CIM_RegisteredProfile.mof")
#pragma include ("DMTF/Interop/CIM_RegisteredSubProfile.mof")
#pragma include ("DMTF/Interop/CIM_SystemIdentification.mof")
#pragma include ("DMTF/Interop/CIM_SystemInNamespace.mof")
#pragma include ("DMTF/Interop/CIM_ElementConformsToProfile.mof")
#pragma include ("DMTF/Interop/CIM_ReferencedSpecification.mof")
#pragma include ("DMTF/Interop/CIM_ReferencedProfile.mof")
#pragma include ("DMTF/Interop/CIM_SubProfileRequiresProfile.mof")
#pragma include ("DMTF/Interop/CIM_IdentificationOfManagedSystem.mof")
#pragma include ("DMTF/Interop/CIM_ObjectManagerCommunicationMechanism.mof")
#pragma include ("DMTF/Interop/CIM_WBEMService.mof")
#pragma include ("DMTF/Interop/CIM_CIMXMLCommunicationMechanism.mof")
#pragma include ("DMTF/Interop/CIM_ObjectManager.mof")
#pragma include ("DMTF/Interop/CIM_ObjectManagerAdapter.mof")
#pragma include ("DMTF/Interop/CIM_ProtocolAdapter.mof")
#pragma include ("DMTF/Interop/CIM_CommMechanismForAdapter.mof")
#pragma include ("DMTF/Interop/CIM_CommMechanismForManager.mof")
#pragma include ("DMTF/Interop/CIM_CommMechanismForObjectManagerAdapter.mof")
#pragma include ("DMTF/Interop/CIM_NamespaceInManager.mof")
 
