/***************************************************************************//*! \file liprovider/SF_API_Provider.h
** <L5_PRIVATE L5_SOURCE>
** \author  OktetLabs
**  \brief  CIM Provider
**   \date  2018/03/22
**    \cop  (c) Solarflare Communications Inc.
** </L5_PRIVATE>
*//*
\**************************************************************************/

// Generated by genprov 2.0.24
#ifndef _SF_API_Provider_h
#define _SF_API_Provider_h

#include <cimple/cimple.h>
#include "SF_API.h"
#include "sf_platform.h"

CIMPLE_NAMESPACE_BEGIN

class SF_API_Provider
{
public:

    typedef SF_API Class;

    SF_API_Provider();

    ~SF_API_Provider();

    Load_Status load();

    Unload_Status unload();

    Get_Instance_Status get_instance(
        const SF_API* model,
        SF_API*& instance);

    Enum_Instances_Status enum_instances(
        const SF_API* model,
        Enum_Instances_Handler<SF_API>* handler);

    Create_Instance_Status create_instance(
        SF_API* instance);

    Delete_Instance_Status delete_instance(
        const SF_API* instance);

    Modify_Instance_Status modify_instance(
        const SF_API* model,
        const SF_API* instance);

    Invoke_Method_Status GetPFVFByPCI(
        const SF_API* self,
        const Property<String>& PCIAddr,
        Property<uint32>& PF,
        Property<uint32>& VF,
        Property<String>& NICTag,
        Property<uint32>& return_value);

    Invoke_Method_Status GetFuncPrivileges(
        const SF_API* self,
        const Property<uint32> &PhysicalFunction,
        const Property<uint32> &VirtualFunction,
        const Property<String> &PCIAddr,
        const Property<String> &CallingDev,
        Property<Array_String>& PrivilegeNames,
        Property<Array_uint32>& Privileges,
        Property<uint32>& return_value);

    Invoke_Method_Status ModifyFuncPrivileges(
        const SF_API* self,
        const Property<uint32> &PhysicalFunction,
        const Property<uint32> &VirtualFunction,
        const Property<String> &PCIAddr,
        const Property<String> &CallingDev,
        const Property<String>& AddedMask,
        const Property<String>& RemovedMask,
        Property<uint32>& return_value);

    /*@END@*/
};

CIMPLE_NAMESPACE_END

#endif /* _SF_API_Provider_h */
