/***************************************************************************//*! \file liprovider/SF_ConnectorRealizesController_Provider.cpp
** <L5_PRIVATE L5_SOURCE>
** \author  OktetLabs
**  \brief  CIM Provider
**   \date  2013/10/02
**    \cop  (c) Solarflare Communications Inc.
** </L5_PRIVATE>
*//*
\**************************************************************************/

// Generated by genprov 2.0.24
#include "SF_ConnectorRealizesController_Provider.h"
#include "SF_EthernetPort_Provider.h"
#include "SF_PhysicalConnector_Provider.h"
#include "sf_provider.h"

CIMPLE_NAMESPACE_BEGIN

SF_ConnectorRealizesController_Provider::SF_ConnectorRealizesController_Provider()
{
}

SF_ConnectorRealizesController_Provider::~SF_ConnectorRealizesController_Provider()
{
}

Load_Status SF_ConnectorRealizesController_Provider::load()
{
    solarflare::System::target.initialize();
    return LOAD_OK;
}

Unload_Status SF_ConnectorRealizesController_Provider::unload()
{
    return UNLOAD_OK;
}

Get_Instance_Status SF_ConnectorRealizesController_Provider::get_instance(
    const SF_ConnectorRealizesController* model,
    SF_ConnectorRealizesController*& instance)
{
    return GET_INSTANCE_UNSUPPORTED;
}

Enum_Instances_Status SF_ConnectorRealizesController_Provider::enum_instances(
    const SF_ConnectorRealizesController* model,
    Enum_Instances_Handler<SF_ConnectorRealizesController>* handler)
{
    solarflare::EnumInstances<SF_ConnectorRealizesController>::allInterfaces(handler);
    return ENUM_INSTANCES_OK;
}

Create_Instance_Status SF_ConnectorRealizesController_Provider::create_instance(
    SF_ConnectorRealizesController* instance)
{
    return CREATE_INSTANCE_UNSUPPORTED;
}

Delete_Instance_Status SF_ConnectorRealizesController_Provider::delete_instance(
    const SF_ConnectorRealizesController* instance)
{
    return DELETE_INSTANCE_UNSUPPORTED;
}

Modify_Instance_Status SF_ConnectorRealizesController_Provider::modify_instance(
    const SF_ConnectorRealizesController* model,
    const SF_ConnectorRealizesController* instance)
{
    return MODIFY_INSTANCE_UNSUPPORTED;
}

Enum_Associator_Names_Status SF_ConnectorRealizesController_Provider::enum_associator_names(
    const Instance* instance,
    const String& result_class,
    const String& role,
    const String& result_role,
    Enum_Associator_Names_Handler<Instance>* handler)
{
    return ENUM_ASSOCIATOR_NAMES_UNSUPPORTED;
}

Enum_Associators_Status SF_ConnectorRealizesController_Provider::enum_associators(
    const Instance* instance,
    const String& result_class,
    const String& role,
    const String& result_role,
    Enum_Associators_Handler<Instance>* handler)
{
    return ENUM_ASSOCIATORS_UNSUPPORTED;
}

Enum_References_Status SF_ConnectorRealizesController_Provider::enum_references(
    const Instance* instance,
    const SF_ConnectorRealizesController* model,
    const String& role,
    Enum_References_Handler<SF_ConnectorRealizesController>* handler)
{
    return ENUM_REFERENCES_UNSUPPORTED;
}

/*@END@*/

CIMPLE_NAMESPACE_END
