/***************************************************************************//*! \file liprovider/SF_DiagnosticLogCapabilities_Provider.h
** <L5_PRIVATE L5_SOURCE>
** \author  OktetLabs
**  \brief  CIM Provider
**   \date  2013/10/02
**    \cop  (c) Solarflare Communications Inc.
** </L5_PRIVATE>
*//*
\**************************************************************************/

// Generated by genprov 2.0.24
#ifndef _SF_DiagnosticLogCapabilities_Provider_h
#define _SF_DiagnosticLogCapabilities_Provider_h

#include <cimple/cimple.h>
#include "SF_DiagnosticLogCapabilities.h"
#include "sf_provider.h"

CIMPLE_NAMESPACE_BEGIN

class SF_DiagnosticLogCapabilities_Provider
{

public:

    typedef SF_DiagnosticLogCapabilities Class;

    SF_DiagnosticLogCapabilities_Provider();

    ~SF_DiagnosticLogCapabilities_Provider();

    Load_Status load();

    Unload_Status unload();

    Get_Instance_Status get_instance(
        const SF_DiagnosticLogCapabilities* model,
        SF_DiagnosticLogCapabilities*& instance);

    Enum_Instances_Status enum_instances(
        const SF_DiagnosticLogCapabilities* model,
        Enum_Instances_Handler<SF_DiagnosticLogCapabilities>* handler);

    Create_Instance_Status create_instance(
        SF_DiagnosticLogCapabilities* instance);

    Delete_Instance_Status delete_instance(
        const SF_DiagnosticLogCapabilities* instance);

    Modify_Instance_Status modify_instance(
        const SF_DiagnosticLogCapabilities* model,
        const SF_DiagnosticLogCapabilities* instance);

#if CIM_SCHEMA_VERSION_MINOR < 28
    Invoke_Method_Status CreateGoalSettings(
        const SF_DiagnosticLogCapabilities* self,
        const Property< Array<CIM_SettingData*> >& TemplateGoalSettings,
        Property< Array<CIM_SettingData*> >& SupportedGoalSettings,
        Property<uint16>& return_value);
#endif

    /*@END@*/
};

CIMPLE_NAMESPACE_END

#endif /* _SF_DiagnosticLogCapabilities_Provider_h */
