/***************************************************************************//*! \file liprovider/SF_DriverSoftwareIdentity_Provider.h
** <L5_PRIVATE L5_SOURCE>
** \author  OktetLabs
**  \brief  CIM Provider
**   \date  2013/10/02
**    \cop  (c) Solarflare Communications Inc.
** </L5_PRIVATE>
*//*
\**************************************************************************/

// Generated by genprov 2.0.24
#ifndef _SF_DriverSoftwareIdentity_Provider_h
#define _SF_DriverSoftwareIdentity_Provider_h

#include <cimple/cimple.h>
#include "SF_DriverSoftwareIdentity.h"
#include "sf_provider.h"

CIMPLE_NAMESPACE_BEGIN

class SF_DriverSoftwareIdentity_Provider
{
public:
    typedef SF_DriverSoftwareIdentity Class;

    SF_DriverSoftwareIdentity_Provider();

    ~SF_DriverSoftwareIdentity_Provider();

    Load_Status load();

    Unload_Status unload();

    Get_Instance_Status get_instance(
        const SF_DriverSoftwareIdentity* model,
        SF_DriverSoftwareIdentity*& instance);

    Enum_Instances_Status enum_instances(
        const SF_DriverSoftwareIdentity* model,
        Enum_Instances_Handler<SF_DriverSoftwareIdentity>* handler);

    Create_Instance_Status create_instance(
        SF_DriverSoftwareIdentity* instance);

    Delete_Instance_Status delete_instance(
        const SF_DriverSoftwareIdentity* instance);

    Modify_Instance_Status modify_instance(
        const SF_DriverSoftwareIdentity* model,
        const SF_DriverSoftwareIdentity* instance);

#if defined(TARGET_CIM_SERVER_esxi) || defined(TARGET_CIM_SERVER_esxi_native)
    Invoke_Method_Status GetDriverLoadParameters(
        const SF_DriverSoftwareIdentity* self,
        Property<String>& LoadParameters,
        Property<uint32>& return_value);

    Invoke_Method_Status SetDriverLoadParameters(
        const SF_DriverSoftwareIdentity* self,
        const Property<String>& LoadParameters,
        Property<uint32>& return_value);
#endif
    /*@END@*/
};

CIMPLE_NAMESPACE_END

#endif /* _SF_DriverSoftwareIdentity_Provider_h */
