// Generated by genprov 2.0.24
#ifndef _SF_JobSuccess_Provider_h
#define _SF_JobSuccess_Provider_h

#include <cimple/cimple.h>
#include "SF_JobSuccess.h"

CIMPLE_NAMESPACE_BEGIN

class SF_JobSuccess_Provider
{
public:

    typedef SF_JobSuccess Class;

    SF_JobSuccess_Provider();

    ~SF_JobSuccess_Provider();

    Load_Status load();

    Unload_Status unload();

    Enable_Indications_Status enable_indications(
        Indication_Handler<SF_JobSuccess>* indication_handler);

    Disable_Indications_Status disable_indications();

    /*@END@*/
};

CIMPLE_NAMESPACE_END

#endif /* _SF_JobSuccess_Provider_h */
