// Generated by genprov 2.0.24
#ifndef _SF_JobProgress_Provider_h
#define _SF_JobProgress_Provider_h

#include <cimple/cimple.h>
#include "SF_JobProgress.h"

CIMPLE_NAMESPACE_BEGIN

class SF_JobProgress_Provider
{
public:

    typedef SF_JobProgress Class;

    SF_JobProgress_Provider();

    ~SF_JobProgress_Provider();

    Load_Status load();

    Unload_Status unload();

    Enable_Indications_Status enable_indications(
        Indication_Handler<SF_JobProgress>* indication_handler);

    Disable_Indications_Status disable_indications();

    /*@END@*/
};

CIMPLE_NAMESPACE_END

#endif /* _SF_JobProgress_Provider_h */
