/***************************************************************************//*! \file liprovider/SF_NVAPI_Provider.cpp
** <L5_PRIVATE L5_SOURCE>
** \author  OktetLabs
**  \brief  CIM Provider
**   \date  2013/10/02
**    \cop  (c) Solarflare Communications Inc.
** </L5_PRIVATE>
*//*
\**************************************************************************/

// Generated by genprov 2.0.24
#include "SF_NVAPI_Provider.h"
#include "sf_provider.h"

CIMPLE_NAMESPACE_BEGIN

enum ReturnValue 
{
    OK = 0,
    Error = 2,
    InvalidParameter = 5,
};

using namespace solarflare;

SF_NVAPI_Provider::SF_NVAPI_Provider()
{
}

SF_NVAPI_Provider::~SF_NVAPI_Provider()
{
}

Load_Status SF_NVAPI_Provider::load()
{
    solarflare::CIMHelper::initialize();
    return LOAD_OK;
}

Unload_Status SF_NVAPI_Provider::unload()
{
    return UNLOAD_OK;
}

Get_Instance_Status SF_NVAPI_Provider::get_instance(
    const SF_NVAPI* model,
    SF_NVAPI*& instance)
{
    return GET_INSTANCE_UNSUPPORTED;
}

Enum_Instances_Status SF_NVAPI_Provider::enum_instances(
    const SF_NVAPI* model,
    Enum_Instances_Handler<SF_NVAPI>* handler)
{
    SF_NVAPI *inst = SF_NVAPI::create();
 
    if (inst == NULL)
        return ENUM_INSTANCES_FAILED;

    inst->ElementName.set("NVAPI");
    inst->Description.set("Remote access to NV API");
    inst->Caption.set("Remote access to NV API");

    handler->handle(inst);
    return ENUM_INSTANCES_OK;
}

Create_Instance_Status SF_NVAPI_Provider::create_instance(
    SF_NVAPI* instance)
{
    return CREATE_INSTANCE_UNSUPPORTED;
}

Delete_Instance_Status SF_NVAPI_Provider::delete_instance(
    const SF_NVAPI* instance)
{
    return DELETE_INSTANCE_UNSUPPORTED;
}

Modify_Instance_Status SF_NVAPI_Provider::modify_instance(
    const SF_NVAPI* model,
    const SF_NVAPI* instance)
{
    return MODIFY_INSTANCE_UNSUPPORTED;
}

Invoke_Method_Status SF_NVAPI_Provider::getSFUDevices(
    const SF_NVAPI* self,
    Property<String>& Devices,
    Property<uint32>& return_value)
{
    String devs = solarflare::System::target.getSFUDevices();

    if (devs.empty())
    {
        Devices.null = true;
        return_value.set(Error);
    }
    else
    {
        Devices.null = false;
        Devices.value = devs;
        return_value.set(OK);
    }

    return INVOKE_METHOD_OK;
}

Invoke_Method_Status SF_NVAPI_Provider::NVExists(
    const SF_NVAPI* self,
    const Property<String>& Device,
    const Property<uint32>& Type,
    const Property<uint32>& Subtype,
    const Property<boolean>& TryOtherDevs,
    Property<boolean>& Exists,
    Property<String>& CorrectDevice,
    Property<uint32>& return_value)
{
    String  correct_dev;
    boolean try_other_devs = false;

    if (Device.null || Device.value.empty() ||
        Type.null || Subtype.null)
    {
        PROVIDER_LOG_ERR("%s(): necessary parameters "
                         "should be specified",
                         __FUNCTION__);
        return_value.set(InvalidParameter);
        return INVOKE_METHOD_OK;
    }

    if (!TryOtherDevs.null)
        try_other_devs = TryOtherDevs.value;

    Exists.null = false;
    if (solarflare::System::target.NVExists(Device.value,
                                            Type.value,
                                            Subtype.value,
                                            try_other_devs,
                                            correct_dev))
    {
        Exists.value = true;
        if (try_other_devs)
        {
            CorrectDevice.null = false;
            CorrectDevice.value = correct_dev;
        }
    }
    else
        Exists.value = false;

    return_value.set(OK);
    return INVOKE_METHOD_OK;
}

Invoke_Method_Status SF_NVAPI_Provider::NVOpen(
    const SF_NVAPI* self,
    const Property<String>& Device,
    const Property<uint32>& Type,
    const Property<uint32>& Subtype,
    Property<uint32>& NVContext,
    Property<uint32>& return_value)
{
    int nv_cntx;

    if (Device.null || Device.value.empty() ||
        Type.null || Subtype.null)
    {
        PROVIDER_LOG_ERR("%s(): necessary parameters "
                         "should be specified",
                         __FUNCTION__);
        return_value.set(InvalidParameter);
        return INVOKE_METHOD_OK;
    }
    
    nv_cntx = solarflare::System::target.NVOpen(Device.value,
                                                Type.value,
                                                Subtype.value);

    if (nv_cntx < 0)
    {
        NVContext.null = true;
        return_value.set(Error);
    }
    else
    {
        NVContext.null = false;
        NVContext.value = nv_cntx;
        return_value.set(OK);
    }

    return INVOKE_METHOD_OK;
}

Invoke_Method_Status SF_NVAPI_Provider::NVClose(
    const SF_NVAPI* self,
    const Property<uint32>& NVContext,
    Property<uint32>& return_value)
{
    if (NVContext.null)
    {
        PROVIDER_LOG_ERR("%s(): NV context "
                         "should be specified",
                         __FUNCTION__);
        return_value.set(InvalidParameter);
        return INVOKE_METHOD_OK;
    }

    if (solarflare::System::target.NVClose(NVContext.value) < 0)
        return_value.set(Error);
    else
        return_value.set(OK);

    return INVOKE_METHOD_OK;
}

Invoke_Method_Status SF_NVAPI_Provider::NVPartSize(
    const SF_NVAPI* self,
    const Property<uint32>& NVContext,
    Property<uint64>& PartSize,
    Property<uint32>& return_value)
{
    uint64 part_size;

    if (NVContext.null)
    {
        PROVIDER_LOG_ERR("%s(): NV context "
                         "should be specified",
                         __FUNCTION__);
        return_value.set(InvalidParameter);
        return INVOKE_METHOD_OK;
    }

    part_size = solarflare::System::target.NVPartSize(NVContext.value);

    PartSize.null = false;
    PartSize.value = part_size;
    return_value.set(OK);

    return INVOKE_METHOD_OK;
}

Invoke_Method_Status SF_NVAPI_Provider::NVRead(
    const SF_NVAPI* self,
    const Property<uint32>& NVContext,
    const Property<uint64>& Length,
    const Property<sint64>& Offset,
    Property<String>& Data,
    Property<uint32>& return_value)
{
    int rc;

    if (NVContext.null || Length.null || Offset.null)
    {
        PROVIDER_LOG_ERR("%s(): some parameters "
                         "are missed",
                         __FUNCTION__);
        return_value.set(InvalidParameter);
        return INVOKE_METHOD_OK;
    }

    rc = solarflare::System::target.NVRead(NVContext.value,
                                           Length.value,
                                           Offset.value,
                                           Data.value);

    if (rc >= 0)
    {
        Data.null = false;
        return_value.set(OK);
    }
    else
        return_value.set(Error);

    return INVOKE_METHOD_OK;
}

Invoke_Method_Status SF_NVAPI_Provider::NVReadAll(
    const SF_NVAPI* self,
    const Property<uint32>& NVContext,
    Property<String>& Data,
    Property<uint32>& return_value)
{
    int rc;

    if (NVContext.null)
    {
        PROVIDER_LOG_ERR("%s(): some parameters "
                         "are missed",
                         __FUNCTION__);
        return_value.set(InvalidParameter);
        return INVOKE_METHOD_OK;
    }

    rc = solarflare::System::target.NVReadAll(NVContext.value,
                                              Data.value);

    if (rc >= 0)
    {
        Data.null = false;
        return_value.set(OK);
    }
    else
        return_value.set(Error);

    return INVOKE_METHOD_OK;
}

Invoke_Method_Status SF_NVAPI_Provider::NVWriteAll(
    const SF_NVAPI* self,
    const Property<uint32>& NVContext,
    const Property<String>& Data,
    Property<uint32>& return_value)
{
    int rc;

    if (NVContext.null)
    {
        PROVIDER_LOG_ERR("%s(): some parameters "
                         "are missed",
                         __FUNCTION__);
        return_value.set(InvalidParameter);
        return INVOKE_METHOD_OK;
    }

    rc = solarflare::System::target.NVWriteAll(NVContext.value,
                                               Data.value);

    if (rc >= 0)
        return_value.set(OK);
    else
        return_value.set(Error);

    return INVOKE_METHOD_OK;
}

Invoke_Method_Status SF_NVAPI_Provider::MCDIV1Command(
    const SF_NVAPI* self,
    const Property<String>& Device,
    Property<uint32>& Command,
    Property<uint32>& Len,
    Property<uint32>& RC,
    Property<String>& Payload,
    Property<sint32>& Ioctl_rc,
    Property<uint32>& Ioctl_errno,
    Property<uint32>& return_value)
{
    int rc;

    unsigned int cmd = 0;
    unsigned int len = 0;
    unsigned int cmd_rc = 0;
    int ioctl_rc = 0;
    unsigned int ioctl_errno = 0;

    if (Device.null || Command.null || Len.null || Payload.null)
    {
        PROVIDER_LOG_ERR("%s(): some parameters "
                         "are missed",
                         __FUNCTION__);
        return_value.set(InvalidParameter);
        return INVOKE_METHOD_OK;
    }

    cmd = Command.value;
    len = Len.value;
    if (!RC.null)
        cmd_rc = RC.value;

    rc = solarflare::System::target.MCDIV1Command(Device.value,
                                                  cmd, len, cmd_rc,
                                                  Payload.value,
                                                  ioctl_rc, ioctl_errno);
    if (rc >= 0)
        return_value.set(OK);
    else
        return_value.set(Error);

    Command.set(cmd);
    Len.set(len);
    RC.set(cmd_rc);
    Ioctl_rc.set(ioctl_rc);
    Ioctl_errno.set(ioctl_errno);

    return INVOKE_METHOD_OK;
}

Invoke_Method_Status SF_NVAPI_Provider::MCDIV2Command(
    const SF_NVAPI* self,
    const Property<String>& Device,
    Property<uint32>& Command,
    Property<uint32>& InLen,
    Property<uint32>& OutLen,
    Property<uint32>& Flags,
    Property<String>& Payload,
    Property<uint32>& Host_errno,
    Property<sint32>& Ioctl_rc,
    Property<uint32>& Ioctl_errno,
    Property<uint32>& return_value)
{
    int rc;

    unsigned int cmd = 0;
    unsigned int inlen = 0;
    unsigned int outlen = 0;
    unsigned int flags = 0;
    unsigned int host_errno = 0;
    int ioctl_rc = 0;
    unsigned int ioctl_errno = 0;

    if (Device.null || Command.null || InLen.null || OutLen.null ||
        Payload.null)
    {
        PROVIDER_LOG_ERR("%s(): some parameters "
                         "are missed",
                         __FUNCTION__);
        return_value.set(InvalidParameter);
        return INVOKE_METHOD_OK;
    }

    cmd = Command.value;
    inlen = InLen.value;
    outlen = OutLen.value;
    if (!Flags.null)
        flags = Flags.value;
    if (!Host_errno.null)
        host_errno = Host_errno.value;

    rc = solarflare::System::target.MCDIV2Command(Device.value,
                                                  cmd, inlen, outlen,
                                                  flags,
                                                  Payload.value,
                                                  host_errno,
                                                  ioctl_rc, ioctl_errno);
    if (rc >= 0)
        return_value.set(OK);
    else
        return_value.set(Error);

    Command.set(cmd);
    InLen.set(inlen);
    OutLen.set(outlen);
    Flags.set(flags);
    Host_errno.set(host_errno);
    Ioctl_rc.set(ioctl_rc);
    Ioctl_errno.set(ioctl_errno);

    return INVOKE_METHOD_OK;
}

Invoke_Method_Status SF_NVAPI_Provider::MCDIRead(
    const SF_NVAPI* self,
    const Property<String>& Device,
    const Property<uint32>& PartitionType,
    const Property<uint32>& Length,
    const Property<uint32>& Offset,
    Property<String>& Data,
    Property<uint32>& return_value)
{
    int rc;

    if (Device.null || PartitionType.null || Length.null || Offset.null)
    {
        PROVIDER_LOG_ERR("%s(): some parameters "
                         "are missed",
                         __FUNCTION__);
        return_value.set(InvalidParameter);
        return INVOKE_METHOD_OK;
    }

    rc = solarflare::System::target.MCDIRead(Device.value,
                                             PartitionType.value,
                                             Length.value,
                                             Offset.value,
                                             Data.value);
    if (rc >= 0)
    {
        Data.null = false;
        return_value.set(OK);
    }
    else
        return_value.set(Error);

    return INVOKE_METHOD_OK;
}

Invoke_Method_Status SF_NVAPI_Provider::MCDIWrite(
    const SF_NVAPI* self,
    const Property<String>& Device,
    const Property<uint32>& PartitionType,
    const Property<uint32>& Offset,
    const Property<String>& Data,
    Property<uint32>& return_value)
{
    int rc;

    if (Device.null || PartitionType.null || Offset.null ||
        Data.null)
    {
        PROVIDER_LOG_ERR("%s(): some parameters "
                         "are missed",
                         __FUNCTION__);
        return_value.set(InvalidParameter);
        return INVOKE_METHOD_OK;
    }

    rc = solarflare::System::target.MCDIWrite(Device.value,
                                              PartitionType.value,
                                              Offset.value,
                                              Data.value);
    if (rc >= 0)
        return_value.set(OK);
    else
        return_value.set(Error);

    return INVOKE_METHOD_OK;
}

/*@END@*/

CIMPLE_NAMESPACE_END
