/***************************************************************************//*! \file liprovider/SF_PackageSoftwareIdentity_Provider.h
** <L5_PRIVATE L5_SOURCE>
** \author  OktetLabs
**  \brief  CIM Provider
**   \date  2013/10/02
**    \cop  (c) Solarflare Communications Inc.
** </L5_PRIVATE>
*//*
\**************************************************************************/

// Generated by genprov 2.0.24
#ifndef _SF_PackageSoftwareIdentity_Provider_h
#define _SF_PackageSoftwareIdentity_Provider_h

#include <cimple/cimple.h>
#include "SF_PackageSoftwareIdentity.h"
#include "sf_provider.h"

CIMPLE_NAMESPACE_BEGIN

class SF_PackageSoftwareIdentity_Provider
{
public:
    typedef SF_PackageSoftwareIdentity Class;

    SF_PackageSoftwareIdentity_Provider();

    ~SF_PackageSoftwareIdentity_Provider();

    Load_Status load();

    Unload_Status unload();

    Get_Instance_Status get_instance(
        const SF_PackageSoftwareIdentity* model,
        SF_PackageSoftwareIdentity*& instance);

    Enum_Instances_Status enum_instances(
        const SF_PackageSoftwareIdentity* model,
        Enum_Instances_Handler<SF_PackageSoftwareIdentity>* handler);

    Create_Instance_Status create_instance(
        SF_PackageSoftwareIdentity* instance);

    Delete_Instance_Status delete_instance(
        const SF_PackageSoftwareIdentity* instance);

    Modify_Instance_Status modify_instance(
        const SF_PackageSoftwareIdentity* model,
        const SF_PackageSoftwareIdentity* instance);

    /*@END@*/
};

CIMPLE_NAMESPACE_END

#endif /* _SF_PackageSoftwareIdentity_Provider_h */
