// Generated by genprov 2.0.24
#include "SF_RegisteredProfile_Provider.h"
#include "sf_provider.h"

CIMPLE_NAMESPACE_BEGIN


SF_RegisteredProfile_Provider::SF_RegisteredProfile_Provider()
{
}

SF_RegisteredProfile_Provider::~SF_RegisteredProfile_Provider()
{
}

Load_Status SF_RegisteredProfile_Provider::load()
{
    solarflare::CIMHelper::initialize();
    return LOAD_OK;
}

Unload_Status SF_RegisteredProfile_Provider::unload()
{
    return UNLOAD_OK;
}

Get_Instance_Status SF_RegisteredProfile_Provider::get_instance(
    const SF_RegisteredProfile* model,
    SF_RegisteredProfile*& instance)
{
    return GET_INSTANCE_UNSUPPORTED;
}

Enum_Instances_Status SF_RegisteredProfile_Provider::enum_instances(
    const SF_RegisteredProfile* model,
    Enum_Instances_Handler<SF_RegisteredProfile>* handler)
{
    solarflare::EnumInstances<SF_RegisteredProfile>::topmost(handler);
    return ENUM_INSTANCES_OK;
}

Create_Instance_Status SF_RegisteredProfile_Provider::create_instance(
    SF_RegisteredProfile* instance)
{
    return CREATE_INSTANCE_UNSUPPORTED;
}

Delete_Instance_Status SF_RegisteredProfile_Provider::delete_instance(
    const SF_RegisteredProfile* instance)
{
    return DELETE_INSTANCE_UNSUPPORTED;
}

Modify_Instance_Status SF_RegisteredProfile_Provider::modify_instance(
    const SF_RegisteredProfile* model,
    const SF_RegisteredProfile* instance)
{
    return MODIFY_INSTANCE_UNSUPPORTED;
}

Invoke_Method_Status SF_RegisteredProfile_Provider::CloseConformantInstances(
    const SF_RegisteredProfile* self,
    const Property<String>& EnumerationContext,
    Property<uint32>& return_value)
{
    return INVOKE_METHOD_UNSUPPORTED;
}

Invoke_Method_Status SF_RegisteredProfile_Provider::OpenConformantInstances(
    const SF_RegisteredProfile* self,
    const Property<String>& ResultClass,
    const Property<Array_String>& IncludedPropertyList,
    const Property<uint32>& OperationTimeout,
    const Property<boolean>& ContinueOnError,
    const Property<uint32>& MaxObjectCount,
    Property<String>& EnumerationContext,
    Property<boolean>& EndOfSequence,
    Property<Array_uint16>& InstanceType,
    Property< Array<CIM_ManagedElement*> >& InstanceWithPathList,
    Property<uint32>& return_value)
{
    return INVOKE_METHOD_UNSUPPORTED;
}

Invoke_Method_Status SF_RegisteredProfile_Provider::PullConformantInstances(
    const SF_RegisteredProfile* self,
    const Property<uint32>& MaxObjectCount,
    Property<String>& EnumerationContext,
    Property<boolean>& EndOfSequence,
    Property<Array_uint16>& InstanceType,
    Property< Array<CIM_ManagedElement*> >& InstanceWithPathList,
    Property<uint32>& return_value)
{
    return INVOKE_METHOD_UNSUPPORTED;
}

/*@END@*/

CIMPLE_NAMESPACE_END
