// Generated by genprov 2.0.24
#ifndef _SF_SystemUseOfLog_Provider_h
#define _SF_SystemUseOfLog_Provider_h

#include <cimple/cimple.h>
#include "SF_SystemUseOfLog.h"
#include "sf_platform.h"

CIMPLE_NAMESPACE_BEGIN

class SF_SystemUseOfLog_Provider
{
public:

    typedef SF_SystemUseOfLog Class;

    SF_SystemUseOfLog_Provider();

    ~SF_SystemUseOfLog_Provider();

    Load_Status load();

    Unload_Status unload();

    Get_Instance_Status get_instance(
        const SF_SystemUseOfLog* model,
        SF_SystemUseOfLog*& instance);

    Enum_Instances_Status enum_instances(
        const SF_SystemUseOfLog* model,
        Enum_Instances_Handler<SF_SystemUseOfLog>* handler);

    Create_Instance_Status create_instance(
        SF_SystemUseOfLog* instance);

    Delete_Instance_Status delete_instance(
        const SF_SystemUseOfLog* instance);

    Modify_Instance_Status modify_instance(
        const SF_SystemUseOfLog* model,
        const SF_SystemUseOfLog* instance);

    Enum_Associator_Names_Status enum_associator_names(
        const Instance* instance,
        const String& result_class,
        const String& role,
        const String& result_role,
        Enum_Associator_Names_Handler<Instance>* handler);

    Enum_Associators_Status enum_associators(
        const Instance* instance,
        const String& result_class,
        const String& role,
        const String& result_role,
        Enum_Associators_Handler<Instance>* handler);

    Enum_References_Status enum_references(
        const Instance* instance,
        const SF_SystemUseOfLog* model,
        const String& role,
        Enum_References_Handler<SF_SystemUseOfLog>* handler);

    /*@END@*/
};

CIMPLE_NAMESPACE_END

#endif /* _SF_SystemUseOfLog_Provider_h */
