/***************************************************************************//*! \file liprovider/SF_SoftwareIdentity_Provider.h
** <L5_PRIVATE L5_SOURCE>
** \author  OktetLabs
**  \brief  CIM Provider
**   \date  2013/10/02
**    \cop  (c) Solarflare Communications Inc.
** </L5_PRIVATE>
*//*
\**************************************************************************/

// Generated by genprov 2.0.24
#ifndef _SF_SoftwareIdentity_Provider_h
#define _SF_SoftwareIdentity_Provider_h

#include <cimple/cimple.h>
#include "SF_SoftwareIdentity.h"
#include "sf_provider.h"

CIMPLE_NAMESPACE_BEGIN

class SF_SoftwareIdentity_Provider
{
public:
    typedef SF_SoftwareIdentity Class;

    SF_SoftwareIdentity_Provider();

    ~SF_SoftwareIdentity_Provider();

    Load_Status load();

    Unload_Status unload();

    Get_Instance_Status get_instance(
        const SF_SoftwareIdentity* model,
        SF_SoftwareIdentity*& instance);

    Enum_Instances_Status enum_instances(
        const SF_SoftwareIdentity* model,
        Enum_Instances_Handler<SF_SoftwareIdentity>* handler);

    Create_Instance_Status create_instance(
        SF_SoftwareIdentity* instance);

    Delete_Instance_Status delete_instance(
        const SF_SoftwareIdentity* instance);

    Modify_Instance_Status modify_instance(
        const SF_SoftwareIdentity* model,
        const SF_SoftwareIdentity* instance);

    /*@END@*/
};

CIMPLE_NAMESPACE_END

#endif /* _SF_SoftwareIdentity_Provider_h */
