[Association]
class SF_InstalledSoftwareIdentity : CIM_InstalledSoftwareIdentity {
};

[Association]
class SF_SystemDevice : CIM_SystemDevice {
};

[Association]
class SF_ServiceAffectsSystem : CIM_ServiceAffectsElement {
      [Override("AffectedElement")]
   CIM_ComputerSystem REF AffectedElement;
};

[Association]
class SF_HostedService : CIM_HostedService {
};

[Association]
class SF_HostedAccessPoint : CIM_HostedAccessPoint {
};

[Association]
class SF_SystemUseOfLog : CIM_UseOfLog {
      [Override("Dependent")]
   CIM_ComputerSystem REF Dependent;
};

[Association]
class SF_ComputerSystemPackage : CIM_ComputerSystemPackage {
};

